
#ifndef EPS_DIAGSRVCS_ISO_H
#define EPS_DIAGSRVCS_ISO_H

FUNC(void, EPSDIAGSRVCS_CODE) ProcessF0FF(P2VAR(uint8, AUTOMATIC, AUTOMATIC) t_SrvcData_Cnt_T_u08, VAR(uint16, AUTOMATIC) RequestDataIdx_Cnt_T_u16);

#endif
