

 
#ifndef APPINIT_CFG_H_
#define APPINIT_CFG_H_

#include "Std_Types.h"


/* Peripheral RAM Parity Test Enables */
#define N2HET1_PARITY_ENABLE  		STD_ON
#define N2HET2_PARITY_ENABLE  		STD_ON
#define N2HET1TU_PARITY_ENABLE  	STD_ON
#define N2HET2TU_PARITY_ENABLE  	STD_ON
#define MIBADC1_PARITY_ENABLE  		STD_ON
#define MIBADC2_PARITY_ENABLE  		STD_ON
#define DCAN1_PARITY_ENABLE  		STD_ON
#define DCAN2_PARITY_ENABLE  		STD_ON
#define VIM_PARITY_ENABLE  			STD_ON
#define DMA_PARITY_ENABLE  			STD_ON
#define DMA_MPU_ENABLE  			STD_ON
#define N2HET1TU_MPU_ENABLE  		STD_ON
#define N2HET2TU_MPU_ENABLE  		STD_ON
#endif /* APPINIT_CFG_H_ */
