/*****************************************************************************
* Copyright 2010 Nxtr Automotive, All Rights Reserved.
* Nxtr Confidential
*
* Module File Name  : SpiNxt_Irq.c
* Module Description: Nxtr SPI driver Irq Isr's
* Product           : Gen II Plus - EA3.0
* Author            : Jeremy Warmbier
*****************************************************************************/
/*---------------------------------------------------------------------------
* Version Control:
* Date Created:      Tue Sep 20 16:33:22 2011
* %version:          3 %
* %derived_by:       zz4r1x %
* %date_modified:    Fri Mar 22 11:22:02 2013 %
 *---------------------------------------------------------------------------------------------------------------------
 * Date      Rev      Author         Change Description                                                        SCR #
 * -------   -------  --------  ---------------------------------------------------------------------------  ----------
 * 03/05/12  1        JW             Inital Component Creation
 * 03/18/13  1.1.1    KJS            QAC fixes
 * 03/21/13  2        BWL            Added metrics hooks
*---------------------------------------------------------------------------*/


#include "SpiNxt.h"
#include "Os.h"
#include "Dio.h"
#include "Metrics.h"

/* PRQA S 303 ++ 
 * MISRA Rule 11.3 violation. This deviation is required for register access.  The rule is suppressed for the entire 
 * file due to the frequency of usage throughout this driver.  Annotation at each deviation unecessarily clutters the file.
 */

/*
 * MISRA Rule 14.2 violation. These deviations are required for metrics hooks. These statements are intended to have
 * no effect on production code.
 */

#define SPINXT_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */

/*! \fn void SpiNxt_IrqUnit2TxRx(void)
*   \brief Level 0 Interrupt for MIBSPI3
*/

ISR(SpiNxt_IrqUnit2TxRx)
{
    VAR(uint32, AUTOMATIC) vec;
    VAR(uint32, AUTOMATIC) IntFlgs_Cnt_T_u32;

    /* Metrics start hook does nothing in production build. */
    Metrics_TaskStart(D_SPINXT1_CNT_U08); /* PRQA S 3112 */

    vec = mibspiREG3->INTVECT0;
    IntFlgs_Cnt_T_u32 = mibspiREG3->INTFLGRDY;

    if (vec > 0x21U)
    {
        uint32 flags_Cnt_T_u32 = mibspiREG3->FLG & (~mibspiREG3->LVL & 0x035FU); 
        mibspiREG3->FLG = flags_Cnt_T_u32; 
        mibspiNotification(mibspiREG3, flags_Cnt_T_u32); 
    }
    else
    {
        mibspiGroupNotification(mibspiREG3, ((vec & 0x3FU) >> 1U) - 1U); 
    }

    /* Clear Transfer Group  Interrupt Flags that were processed in this ISR  */
    mibspiREG3->INTFLGRDY = IntFlgs_Cnt_T_u32; 

    /* Metrics end hook does nothing in production build. */
    Metrics_TaskEnd(D_SPINXT1_CNT_U08); /* PRQA S 3112 */
}


/*! \fn void SpiNxt_IrqUnit2TxRxERR(void)
*   \brief Level 1 Interrupt for MIBSPI3
*/

ISR(SpiNxt_IrqUnit2TxRxERR)
{
    VAR(uint32, AUTOMATIC) vec;
    VAR(uint32, AUTOMATIC) IntFlgs_Cnt_T_u32;

    /* Metrics start hook does nothing in production build. */
    Metrics_TaskStart(D_SPINXT2_CNT_U08); /* PRQA S 3112 */

    vec = mibspiREG3->INTVECT1;

    /* Capture Transfer group ISR requests to process in this ISR */
    IntFlgs_Cnt_T_u32= mibspiREG3->INTFLGRDY;

    if (vec > 0x21U)
    {
        uint32 flags_Cnt_T_u32 = mibspiREG3->FLG & (mibspiREG3->LVL & 0x035FU); 
        mibspiREG3->FLG = flags_Cnt_T_u32; 
        mibspiNotification(mibspiREG3, flags_Cnt_T_u32); 
    }
    else
    {
        mibspiGroupNotification(mibspiREG3, ((vec & 0x3FU) >> 1U) - 1U); 
    }
    /* Clear Transfer Group  Interrupt Flags that were processed in this ISR  */
    mibspiREG3->INTFLGRDY = IntFlgs_Cnt_T_u32; 

    /* Metrics end hook does nothing in production build. */
    Metrics_TaskEnd(D_SPINXT2_CNT_U08); /* PRQA S 3112 */
}

#define SPINXT_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */


/*****************************************************************************

CHANGE HISTORY:

 Date      Rev      Author         Change Description              SCR #
-------   -------  --------  -----------------------------------  ----------
03/09/12   1       JJW        Initial file creation
							  Initial API Generated by Halcogen mibspi.c v1.01.000
03/18/13   1.1.1   KJS		  Updated file based on QAC analysis. 
******************************************************************************/

