/* -----------------------------------------------------------------------------
  Filename:    Dem_IntErrId.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\synergy_projects_working\PSA\PSA_BMPV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U

  Generated by , 2016-04-28  10:34:18
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_INTERRID_H)
#define DEM_INTERRID_H

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define CANTRCV_E_NO_TRCV_CONTROL            48
#define PDUR_E_PDU_INSTANCE_LOST             49
#define PDUR_E_INIT_FAILED                   50
#define COMM_E_NET_START_IND_CHANNEL_0       51
#define CAN_E_TIMEOUT                        52
#define CANIF_E_INVALID_DLC                  53
#define CANSM_E_MODE_CHANGE_NETWORK_0        54
#define CANSM_E_MODE_CHANGE_NETWORK_1        55
#define CANSM_E_BUSOFF_NETWORK_0             56
#define CANSM_E_BUSOFF_NETWORK_1             57
#define CANSM_E_SETTRANSCEIVERMODE_NETWORK_0 58
#define CANSM_E_SETTRANSCEIVERMODE_NETWORK_1 59
#define LINSM_E_CONFIRMATION_TIMEOUT         60
#define COMM_E_NET_START_IND_CHANNEL_1       61
#define COMM_E_NET_START_IND_CHANNEL_2       62
#define ECUM_E_ALL_RUN_REQUESTS_KILLED       63
#define ECUM_E_RAM_CHECKED_FAILED            64
#define NVM_E_REQ_FAILED                     65
#define NVM_E_INTEGRITY_FAILED               66
#define FLS_E_ERASE_FAILED                   67
#define FLS_E_WRITE_FAILED                   68
#define FLS_E_READ_FAILED                    69
#define FLS_E_COMPARE_FAILED                 70
#define FRIF_E_JLE_SYNC                      71
#define FRNM_E_INIT_FAILED                   72
#define FRSM_E_CLUSTER_STARTUP               73
#define FRTRCV_E_FR_NO_TRCV_CONTROL          74
#define WDGM_E_SET_MODE                      75
#define WDGM_E_ALIVE_SUPERVISION             76


#endif /* DEM_INTERRID_H */
