/* -----------------------------------------------------------------------------
  Filename:    Dem_IntEvtId.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\Components\PSA_CMP\PSA_CMP_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U

  Generated by , 2018-06-15  14:20:57
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_INTEVTID_H)
#define DEM_INTEVTID_H

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define DEM_EVENT_INVALID                    0
#define CTC_0xD31D83                         1
#define CTC_0xD31D82                         2
#define CTC_0xD31D08                         3
#define CTC_0xD31808                         4
#define CTC_0xD31383                         5
#define CTC_0xD31382                         6
#define CTC_0xD31308                         7
#define CTC_0xD30808                         8
#define CTC_0xD30583                         9
#define CTC_0xD30582                         10
#define CTC_0xD30508                         11
#define CTC_0xD21D81                         12
#define CTC_0xD21881                         13
#define CTC_0xD21381                         14
#define CTC_0xD20881                         15
#define CTC_0xD20581                         16
#define CTC_0xD11D87                         17
#define CTC_0xD11887                         18
#define CTC_0xD11387                         19
#define CTC_0xD10887                         20
#define CTC_0xD10587                         21
#define CTC_0xD00388                         22
#define CTC_0xD00008                         23
#define CTC_0x564404                         24
#define CTC_0x563A8F                         25
#define CTC_0x55668F                         26
#define CTC_0x540D00                         27
#define CTC_0x540C00                         28
#define CTC_0x540B16                         29
#define CTC_0x540698                         30
#define CTC_0x539855                         31
#define CTC_0x520E00                         32
#define CTC_0x520DA2                         33
#define CTC_0x520901                         34
#define CTC_0x513662                         35
#define CTC_0x510C98                         36
#define CTC_0x510C96                         37
#define CTC_0x510C62                         38
#define CTC_0x510C43                         39
#define CTC_0x510C1C                         40
#define CTC_0x510C04                         41
#define CTC_0x510C01                         42
#define CTC_0x510BA3                         43
#define CTC_0x510BA2                         44
#define CTC_0x510BA1                         45
#define CTC_0x510A51                         46
#define CTC_0x050192                         47


#endif /* DEM_INTEVTID_H */
