/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2011 by Vctr Informatik GmbH.                                                  All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vctr Informatik GmbH.
 *                Vctr Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vctr Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  Dio.h
 *    Component:  DrvDio_Tms570Tigio01Asr
 *       Module:  Dio
 *    Generator:  -
 *
 *  Description:  This is the header file of MICROSAR CAL module Dio. This DIO Driver provides services for 
 *                reading and writing to/from
 *                        -   DIO Channels (Pins)
 *                        -   DIO Ports
 *                        -   DIO Channel Groups
 * 
 *                This module works on pins and ports which are configured by the PORT driver for this purpose. 
 *                For this reason there is no configuration and initialization of this port structure in the DIO 
 *                Driver.
 *  
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Project:    EPS.ecuc
 Generated:  2014-01-31 04:28 pm
 Licensee:   Vector AUTOSAR Basic Software (MICROSAR)
 
    This file is generated by DaVinci Configurator Base - DAVINCICFG.EXE V4.0.67.0.
    Do not modify this file, otherwise the software may behave in unexpected way.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Name                          Initials      Company
 *  -------------------------------------------------------------------------------------------------------------------
 *  Tobias Schmid                 Tsd           Vctr Informatik GmbH
 *  Martin Froschhammer           Mfr           Vctr Informatik GmbH      
 *  -------------------------------------------------------------------------------------------------------------------
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Version   Date        Author  Change Id     Description
 *  -------------------------------------------------------------------------------------------------------------------
 *  01.00.00  2008-10-10  Tsd     -             First release
 *  02.01.00  2011-08-19  Mfr     -             Support of Dio_MaskedWritePort added
 *                                -             Version of the code template synchonized with package
 *                                -             Support of HW register access via Safety OS functions
 * 
 *********************************************************************************************************************/

/* module specific MISRA deviations:

 MD_DIO_8.12:
     Reason: The size of the array is not stated explicitly, because the link time configurability can not be guaranteed
             because compiler can optimize the array access depending on its size.
     Risk: Safety decrease
     Prevention: Ensure that array access is always in bound at code inspection 

*/

#if !defined (DIO_CFG_H)
#define DIO_CFG_H

/**********************************************************************************************************************
 *  PUBLIC PART OF CONFIGURATION
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/
/* Configuration file version information */
#define DIO_CFG_MAJOR_VERSION     (2u)
#define DIO_CFG_MINOR_VERSION     (1u)
#define DIO_CFG_PATCH_VERSION     (0u)

#define DIO_INSTANCE_ID           (0u)
#define DIO_DEV_ERROR_DETECT      /*<DIO_DEV_ERROR_DETECT/>*/ (STD_ON)
#define DIO_VERSION_INFO_API      /*<DIO_VERSION_INFO_API/>*/ (STD_ON)
#define DIO_MASKED_WRITE_PORT_API /*<DIO_MASKED_WRITE_PORT_API/>*/ (STD_OFF)

/*<DIO_CFG_CHL_LIST>*/
#define NHet_Ch4    ((Dio_ChannelType) 0x00200000u)
#define NHet_Ch8    ((Dio_ChannelType) 0x01400000u)
#define NHet_Ch15    ((Dio_ChannelType) 0x02780000u)
#define NHet_Ch20    ((Dio_ChannelType) 0x03A00000u)
#define NHet_Ch22    ((Dio_ChannelType) 0x04B00000u)
#define NHet_Ch24    ((Dio_ChannelType) 0x05C00000u)
#define NHet_Ch26    ((Dio_ChannelType) 0x06D00000u)
#define ADC1_Ch0    ((Dio_ChannelType) 0x07040001u)
#define SPI3_NCS1    ((Dio_ChannelType) 0x08080002u)
#define Can3Rx    ((Dio_ChannelType) 0x09010003u)
#define Can3Tx    ((Dio_ChannelType) 0x0A010004u)
#define nERROR    ((Dio_ChannelType) 0x0B000005u)
/*</DIO_CFG_CHL_LIST>*/

/*<DIO_CFG_PORT_LIST>*/
#define NHet    ((Dio_ChannelType) 0x00002E14u)
#define Adc1    ((Dio_ChannelType) 0x01043040u)
#define Spi3    ((Dio_ChannelType) 0x02003E07u)
#define CAN3_Rx    ((Dio_ChannelType) 0x03013879u)
#define CAN3_Tx    ((Dio_ChannelType) 0x04013878u)
#define Esm    ((Dio_ChannelType) 0x05023D49u)
/*</DIO_CFG_PORT_LIST>*/

/********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 *******************************************************************************************************************/
#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*<DIO_CFG_GROUP_LIST>*/
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChGrpNHet;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupAdc1;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupSpi3;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupCan3Rx;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupCan3Tx;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupEsm;
/*</DIO_CFG_GROUP_LIST>*/

#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"


#if ( defined(DIO_SOURCE) || defined(DIO_LCFG_SOURCE) )
  #if !defined(DIO_CFG_PRIVATE_H)
  #define DIO_CFG_PRIVATE_H
  /********************************************************************************************************************
   *  PUBLIC PART OF CONFIGURATION
   *******************************************************************************************************************/

  /********************************************************************************************************************
   *  GLOBAL CONSTANT MACROS
   *******************************************************************************************************************/
  #define DIO_CFG_SUPPORT_GIO           /*<DIO_CFG_SUPPORT_GIO/>*/ (STD_ON)
  #define DIO_CFG_SUPPORT_CAN           /*<DIO_CFG_SUPPORT_CAN/>*/ (STD_ON)

  #if (DIO_DEV_ERROR_DETECT == STD_ON)
    /* development error detection is enabled, allow configuration of parameter checks and error reporting */
    #define DIO_CFG_DO_PARAM_CHECK      /*<DIO_CFG_DO_PARAM_CHECK/>*/ (STD_ON)
    #define DIO_CFG_REPORT_DET              /*<DIO_CFG_REPORT_DET/>*/ (STD_ON)
  #else
    /* development error detection is disabled, so also disable parameter checks and error reporting */
    #define DIO_CFG_DO_PARAM_CHECK      (STD_OFF)
    #define DIO_CFG_REPORT_DET          (STD_OFF)
  #endif

  #if (DIO_CFG_DO_PARAM_CHECK == STD_ON)
    /* parameter checking is enabled, allow configuration of individual checks */
    #define DIO_CFG_CHK_PARAM_CHANNEL   /*<DIO_CFG_CHK_PARAM_CHANNEL/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_PORT         /*<DIO_CFG_CHK_PARAM_PORT/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_GROUP       /*<DIO_CFG_CHK_PARAM_GROUP/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_VINFO       /*<DIO_CFG_CHK_PARAM_VINFO/>*/ (STD_ON)
  #else
    /* parameter checking is disabled, so disable all checks */
    #define DIO_CFG_CHK_PARAM_CHANNEL   (STD_OFF)
    #define DIO_CFG_CHK_PARAM_PORT      (STD_OFF)
    #define DIO_CFG_CHK_PARAM_GROUP     (STD_OFF)
    #define DIO_CFG_CHK_PARAM_VINFO     (STD_OFF)
  #endif


  #define DIO_SPECIAL_REGISTER_ACCESS_ENABLED    /*<DIO_SPECIAL_REGISTER_ACCESS_ENABLED/>*/ (STD_ON)

  #if (STD_ON == DIO_SPECIAL_REGISTER_ACCESS_ENABLED)
    #define DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_WRITE /*<DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_WRITE/>*/ (STD_ON)
    #define DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_PRIVILEGED_MODE_REGISTERS /*<DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_PRIVILEGED_MODE_REGISTERS/>*/ (STD_ON)
  #else
    #define DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_WRITE                                     (STD_OFF)
    #define DIO_SPECIAL_REGISTER_ACCESS_ONLY_FOR_PRIVILEGED_MODE_REGISTERS                 (STD_OFF)
  #endif


  /********************************************************************************************************************
   *  GLOBAL FUNCTION MACROS
   *******************************************************************************************************************/
  #if (DIO_CFG_REPORT_DET == STD_ON)
    /* development error reporting is enabled, allow configuration of Det's include file and function call */
    /*<DIO_CFG_INCLUDE_DET/>*/ #include "Det.h"
    #define Dio_ReportDet(Service, Error) /*<DIO_REPORT_DET/>*/ Det_ReportError(DIO_MODULE_ID, DIO_INSTANCE_ID, Service, Error) /* PRQA S 3453 *//* MD_MSR_19.7 */
  #else
    /* development error reporting is disabled, don't use Det's reporting function */
    #define Dio_ReportDet(Service, Error)
  #endif

  /*<DIO_CFG_INCLUDE_CRITICAL>*/
#include "SchM_Dio.h"
/*</DIO_CFG_INCLUDE_CRITICAL>*/
  #define Dio_EnterCritical()         /*<DIO_CFG_ENTER_CRITICAL/>*/ SchM_Enter_Dio(DIO_EXCLUSIVE_AREA_0)
  #define Dio_ExitCritical()           /*<DIO_CFG_EXIT_CRITICAL/>*/ SchM_Exit_Dio(DIO_EXCLUSIVE_AREA_0)

  /* Include for safety HW register access */
  /*<DIO_CFG_INCLUDE_OS>#include "Os.h"</DIO_CFG_INCLUDE_OS> */

  /********************************************************************************************************************
   *  GLOBAL DATA
   ********************************************************************************************************************/
  #define DIO_START_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
  
    #if (DIO_CFG_CHK_PARAM_CHANNEL == STD_ON)
      /* table containing all configured channels for checking */
      extern CONST(Dio_ChannelType, DIO_CONST) Dio_ChannelCheckTable[]; /* PRQA S 3684 *//* MD_DIO_8.12 */
    #endif
    
    #if (DIO_CFG_CHK_PARAM_PORT == STD_ON)
      /* table containing all configured ports for checking */
      extern CONST(Dio_PortType, DIO_CONST) Dio_PortCheckTable[]; /* PRQA S 3684 *//* MD_DIO_8.12 */
    #endif

    #if (DIO_SPECIAL_REGISTER_ACCESS_ENABLED == STD_ON)

        extern CONST(uint32, DIO_CONST) Dio_PortAddrTable[]; /* PRQA S 3684 *//* MD_DIO_8.12 */

        extern CONST(uint16, DIO_CONST) Dio_PortMemoryAreas[]; /* PRQA S 3684 *//* MD_DIO_8.12 */
    #endif
  
  #define DIO_STOP_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"

  #endif /* DIO_CFG_PRIVATE_H */

#endif  /* ( defined(DIO_SOURCE) || defined(DIO_LCFG_SOURCE) ) */

#endif  /* DIO_CFG_H */

/**********************************************************************************************************************
 *  END OF FILE: Dio_Cfg.h
 *********************************************************************************************************************/
