/* -----------------------------------------------------------------------------
  Filename:    drv_par.h
  Description: Toolversion: 05.00.17.01.30.06.60.01.00.00
               
               Serial Number: CBD1300660
               Customer Info: Nxtr Automotive Corporation
                              Package: CBD Psa SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyDriverBase
               
               Configuration   : C:\Components\PSA_CMP\PSA_CMP_EPS_TMS570\Tools\AsrProject\Config\System\EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "Channel0":
                       Databasefile: C:\Components\PSA_CMP\PSA_CMP_EPS_TMS570\Tools\AsrProject\Config\System\PSA_BMPV.dbc
                       Bussystem:    CAN
                       Manufacturer: PSA
                       Node:         PSCM

  Generated by , 2018-04-12  14:15:17
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DRV_PAR_H__)
#define __DRV_PAR_H__

/* -----------------------------------------------------------------------------
    &&&~ Signal Structures
 ----------------------------------------------------------------------------- */

typedef struct _c_IS_DAT_BSI_432_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 1;
  vbittype Shunt_Position : 2;
  vbittype Power_Supplies : 3;
  vbittype ETAT_PRINCIP_SEV : 2;
  vbittype ETAT_RESEAU_ELEC : 4;
  vbittype unused7 : 4;
} _c_IS_DAT_BSI_432_msgType;
typedef struct _c_IS_DYN2_CMM_348_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 4;
  vbittype ETAT_MT : 4;
} _c_IS_DYN2_CMM_348_msgType;
typedef struct _c_IS_DYN_CMM_208_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 1;
  vbittype DIAG_MUX_ON : 1;
  vbittype unused5 : 6;
} _c_IS_DYN_CMM_208_msgType;
typedef struct _c_IS_DYN_ABR_msgTypeTag
{
  vbittype VITESSE_VEHICULE_ROUES_1 : 8;
  vbittype VITESSE_VEHICULE_ROUES_0 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype CPT_PROCESS_4B_UC_FREIN : 4;
  vbittype CHKSUM_TRME_DYN_UC_FREIN : 4;
} _c_IS_DYN_ABR_msgType;
typedef struct _c_IS_SUPV_DIRA_msgTypeTag
{
  vbittype CODE_DEFAUT : 8;
  vbittype STATUS_CONFABSENT_3 : 8;
  vbittype STATUS_CONFABSENT_2 : 8;
  vbittype STATUS_CONFABSENT_1 : 8;
  vbittype STATUS_CONFABSENT_0 : 8;
  vbittype ETAT_LIGNE_APC : 1;
  vbittype ETAT_ASSIST_DA : 3;
  vbittype unused0 : 4;
} _c_IS_SUPV_DIRA_msgType;
typedef struct _c_IS_SUPV_DIRA_IS_SUPV_DIRA_Group_msgTypeTag
{
  vbittype IS_SUPV_DIRA_Group_5 : 8;
  vbittype IS_SUPV_DIRA_Group_4 : 8;
  vbittype IS_SUPV_DIRA_Group_3 : 8;
  vbittype IS_SUPV_DIRA_Group_2 : 8;
  vbittype IS_SUPV_DIRA_Group_1 : 8;
  vbittype IS_SUPV_DIRA_Group_0 : 4;
  vbittype unused0 : 4;
} _c_IS_SUPV_DIRA_IS_SUPV_DIRA_Group_msgType;
typedef struct _c_IS_DAT_DIRA_msgTypeTag
{
  vbittype CPLE_VOLANT : 8;
  vbittype ETAT_DA_2010 : 2;
  vbittype ETAT_DA_DYN : 2;
  vbittype unused0 : 2;
  vbittype ETAT_DA_2004 : 2;
  vbittype DDE_REDEM_DA : 1;
  vbittype unused1 : 1;
  vbittype AUTOR_ARRET_MOT_DA : 1;
  vbittype EPS_STATE_LKA : 3;
  vbittype STEERWHL_HOLD_BY_DRV : 1;
  vbittype TRQ_LIMIT_STATE : 1;
  vbittype Reserved : 8;
} _c_IS_DAT_DIRA_msgType;
typedef struct _c_IS_DAT_DIRA_IS_DAT_DIRA_Group_msgTypeTag
{
  vbittype IS_DAT_DIRA_Group_2 : 8;
  vbittype IS_DAT_DIRA_Group_1 : 8;
  vbittype IS_DAT_DIRA_Group_0 : 8;
  vbittype cunused0 : 8;
} _c_IS_DAT_DIRA_IS_DAT_DIRA_Group_msgType;
typedef struct _c_IS_DYN_DAE_msgTypeTag
{
  vbittype CHKSUM_TRME_DYN_DAE : 4;
  vbittype CPT_PROCESS_4B_DAE : 4;
  vbittype CPLE_VOLANT_OPTMSE : 8;
  vbittype unused0 : 1;
  vbittype ETAT_DAE_CPK : 2;
  vbittype CAUSE_DESACTIV_CPK : 3;
  vbittype unused1 : 2;
  vbittype ANGLE_COLONNE_1 : 8;
  vbittype ANGLE_COLONNE_0 : 8;
  vbittype VITESSE_COLONNE_1 : 8;
  vbittype VITESSE_COLONNE_0 : 4;
  vbittype ETAT_DAE_CAV3_VIRTUEL : 3;
  vbittype ETAT_SECU_ANGLE_COL : 1;
} _c_IS_DYN_DAE_msgType;
typedef struct _c_IS_DYN_DAE_IS_DYN_DAE_Group_msgTypeTag
{
  vbittype IS_DYN_DAE_Group_6 : 8;
  vbittype IS_DYN_DAE_Group_5 : 8;
  vbittype IS_DYN_DAE_Group_4 : 8;
  vbittype IS_DYN_DAE_Group_3 : 8;
  vbittype IS_DYN_DAE_Group_2 : 8;
  vbittype IS_DYN_DAE_Group_1 : 8;
  vbittype IS_DYN_DAE_Group_0 : 8;
} _c_IS_DYN_DAE_IS_DYN_DAE_Group_msgType;
typedef struct _c_IS_VERS_DIRA_115_msgTypeTag
{
  vbittype System_Code : 8;
  vbittype Download_Day : 8;
  vbittype Download_Month : 8;
  vbittype Download_Year : 8;
  vbittype Application_Code : 8;
  vbittype Software_Version : 8;
  vbittype Software_Edition_MSB : 8;
  vbittype Software_Edition_LSB : 8;
} _c_IS_VERS_DIRA_115_msgType;
typedef struct _c_IS_RES_DIAG_ON_CAN_msgTypeTag
{
  vbittype Diagnostic_Data_Res_7 : 8;
  vbittype Diagnostic_Data_Res_6 : 8;
  vbittype Diagnostic_Data_Res_5 : 8;
  vbittype Diagnostic_Data_Res_4 : 8;
  vbittype Diagnostic_Data_Res_3 : 8;
  vbittype Diagnostic_Data_Res_2 : 8;
  vbittype Diagnostic_Data_Res_1 : 8;
  vbittype Diagnostic_Data_Res_0 : 8;
} _c_IS_RES_DIAG_ON_CAN_msgType;
typedef struct _c_XCP_RES_msgTypeTag
{
  vbittype XCP_Data_Res_7 : 8;
  vbittype XCP_Data_Res_6 : 8;
  vbittype XCP_Data_Res_5 : 8;
  vbittype XCP_Data_Res_4 : 8;
  vbittype XCP_Data_Res_3 : 8;
  vbittype XCP_Data_Res_2 : 8;
  vbittype XCP_Data_Res_1 : 8;
  vbittype XCP_Data_Res_0 : 8;
} _c_XCP_RES_msgType;
typedef struct _c_XCP_REQ_msgTypeTag
{
  vbittype XCP_Data_Req_7 : 8;
  vbittype XCP_Data_Req_6 : 8;
  vbittype XCP_Data_Req_5 : 8;
  vbittype XCP_Data_Req_4 : 8;
  vbittype XCP_Data_Req_3 : 8;
  vbittype XCP_Data_Req_2 : 8;
  vbittype XCP_Data_Req_1 : 8;
  vbittype XCP_Data_Req_0 : 8;
} _c_XCP_REQ_msgType;
typedef struct _c_IS_DAT_BSI_412_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype Req_Mode_DA : 2;
  vbittype unused3 : 6;
} _c_IS_DAT_BSI_412_msgType;
typedef struct _c_IS_DYN_AAS_msgTypeTag
{
  vbittype CONS_ANGLE_CPK_1 : 8;
  vbittype CONS_ANGLE_CPK_0 : 8;
  vbittype DMD_FCT_CPK : 2;
  vbittype DMD_RELAXE_CPK : 2;
  vbittype unused0 : 4;
  vbittype CHKSUM_TRME_DYN_CPK : 4;
  vbittype CPT_PROCESS_4B_CPK : 4;
} _c_IS_DYN_AAS_msgType;
typedef struct _c_IS_DYN_VOL_msgTypeTag
{
  vbittype ANGLE_VOLANT_1 : 8;
  vbittype ANGLE_VOLANT_0 : 8;
  vbittype VITESSE_ROT_VOL : 8;
  vbittype SENS_ROT_VOL : 1;
  vbittype CODE_DEFAUT_VOL : 4;
  vbittype TRIM_VOL : 1;
  vbittype CALIBRATION_VOL : 1;
  vbittype ETAT_CAPT_VOL : 1;
  vbittype CHKSUM_VOL : 4;
  vbittype CPT_PROCESS_4B_A_VOL : 4;
  vbittype VITESSE_ROT_VOL_OPTIMISE : 8;
  vbittype FLG_INIT_AVOL : 1;
  vbittype FLG_AVOL_ICN : 1;
  vbittype ANGLE_VOLANT_ORIGINE : 2;
  vbittype RESERVED : 4;
} _c_IS_DYN_VOL_msgType;
typedef struct _c_IS_DYN_VOL_IS_DYN_VOL_GroupBase_msgTypeTag
{
  vbittype IS_DYN_VOL_GroupBase_4 : 8;
  vbittype IS_DYN_VOL_GroupBase_3 : 8;
  vbittype IS_DYN_VOL_GroupBase_2 : 8;
  vbittype IS_DYN_VOL_GroupBase_1 : 8;
  vbittype IS_DYN_VOL_GroupBase_0 : 8;
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
} _c_IS_DYN_VOL_IS_DYN_VOL_GroupBase_msgType;
typedef struct _c_IS_DYN_VOL_IS_DYN_VOL_GroupAdd_msgTypeTag
{
  vbittype cunused4 : 8;
  vbittype cunused3 : 8;
  vbittype cunused2 : 8;
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
  vbittype IS_DYN_VOL_GroupAdd_1 : 8;
  vbittype IS_DYN_VOL_GroupAdd_0 : 8;
} _c_IS_DYN_VOL_IS_DYN_VOL_GroupAdd_msgType;
typedef struct _c_IS_DAT4_V2_BSI_552_msgTypeTag
{
  vbittype Msg552_Byte0 : 8;
  vbittype Msg552_Byte1 : 8;
  vbittype Msg552_Byte2 : 8;
  vbittype Msg552_Byte3 : 8;
  vbittype Msg552_Byte4 : 8;
  vbittype Msg552_Byte5 : 8;
  vbittype Msg552_Byte6 : 8;
  vbittype Msg552_Byte7 : 8;
} _c_IS_DAT4_V2_BSI_552_msgType;
typedef struct _c_IS_DAT_BSI_3F2_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype DMD_DELEST_DA : 1;
  vbittype unused1 : 2;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 3;
  vbittype LKA_STATE : 3;
  vbittype unused6 : 2;
  vbittype LKA_TRQ_FACT_REQ : 7;
  vbittype LXA_ACTIVATION : 1;
  vbittype COLUMN_ANGLE_SETPOINT_1 : 8;
  vbittype COLUMN_ANGLE_SETPOINT_0 : 6;
  vbittype unused7 : 2;
} _c_IS_DAT_BSI_3F2_msgType;
typedef struct _c_IS_INTE_ELECTRON_BSI_msgTypeTag
{
  vbittype DIAG_INTEGRA_ELEC : 1;
  vbittype MODE_DIAG : 1;
  vbittype unused0 : 5;
  vbittype EFFAC_DEFAULT_DIAG : 1;
} _c_IS_INTE_ELECTRON_BSI_msgType;
typedef struct _c_IS_DYN_CMM_388_msgTypeTag
{
  vbittype VITESSE_VEHICLE_BV_1 : 8;
  vbittype VITESSE_VEHICLE_BV_0 : 8;
} _c_IS_DYN_CMM_388_msgType;
typedef struct _c_IS_ACQ_NEW_JDD_55F_msgTypeTag
{
  vbittype DATA_ACQ_JDD_BSI_2 : 8;
} _c_IS_ACQ_NEW_JDD_55F_msgType;
typedef struct _c_IS_EMIS_NEW_JDD_CAN_DIRA_msgTypeTag
{
  vbittype Number_of_Frames : 2;
  vbittype Frame_Number : 2;
  vbittype DTC_State : 1;
  vbittype unused0 : 1;
  vbittype Type_of_Message : 2;
  vbittype JDD_Byte1 : 8;
  vbittype JDD_Byte2 : 8;
  vbittype JDD_Byte3 : 8;
  vbittype JDD_Byte4 : 8;
  vbittype JDD_Byte5 : 8;
  vbittype JDD_Byte6 : 8;
  vbittype JDD_Byte7 : 8;
} _c_IS_EMIS_NEW_JDD_CAN_DIRA_msgType;
typedef struct _c_IS_ACQ_JDD_CAN_BSI_772_msgTypeTag
{
  vbittype DATA_ACQ_JDD_BSI : 8;
} _c_IS_ACQ_JDD_CAN_BSI_772_msgType;
typedef struct _c_IS_DAT_ABR_50D_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype Regul_ABR : 1;
  vbittype unused1 : 5;
} _c_IS_DAT_ABR_50D_msgType;
typedef struct _c_IS_DYN2_FRE_3CD_msgTypeTag
{
  vbittype Accel_Lat_1 : 8;
  vbittype Accel_Lat_0 : 8;
} _c_IS_DYN2_FRE_3CD_msgType;
typedef struct _c_IS_DYN_CDS_34D_msgTypeTag
{
  vbittype ESP_Deconnecte : 1;
  vbittype Regul_ESP : 1;
  vbittype unused0 : 1;
  vbittype REQ_Lampe_DEF_ESP : 1;
  vbittype unused1 : 4;
} _c_IS_DYN_CDS_34D_msgType;
typedef struct _c_PROTO_HS1_DYN_UCF_5CD_msgTypeTag
{
  vbittype CHKSUM_TRME_DYN_UCF : 4;
  vbittype CPT_PROCESS_4B_UCF : 4;
  vbittype OFFSET_1 : 8;
  vbittype OFFSET_0 : 8;
  vbittype PRECISION_OFFSET : 5;
  vbittype ACQ_INTERRUPT_DAE : 1;
  vbittype unused0 : 2;
} _c_PROTO_HS1_DYN_UCF_5CD_msgType;
typedef struct _c_IS_DAT_BSI_572_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype CONFIG_VHL : 3;
  vbittype unused1 : 5;
} _c_IS_DAT_BSI_572_msgType;
/* -----------------------------------------------------------------------------
    &&&~ Signal Structures for group signals
 ----------------------------------------------------------------------------- */

typedef struct _c_IS_SUPV_DIRA_Group_msgTypeTag
{
  vbittype CODE_DEFAUT : 8;
  vbittype STATUS_CONFABSENT_3 : 8;
  vbittype STATUS_CONFABSENT_2 : 8;
  vbittype STATUS_CONFABSENT_1 : 8;
  vbittype STATUS_CONFABSENT_0 : 8;
  vbittype ETAT_LIGNE_APC : 1;
  vbittype ETAT_ASSIST_DA : 3;
  vbittype unused0 : 4;
} _c_IS_SUPV_DIRA_Group_msgType;
typedef struct _c_IS_DAT_DIRA_Group_msgTypeTag
{
  vbittype CPLE_VOLANT : 8;
  vbittype ETAT_DA_2010 : 2;
  vbittype ETAT_DA_DYN : 2;
  vbittype unused0 : 2;
  vbittype ETAT_DA_2004 : 2;
  vbittype DDE_REDEM_DA : 1;
  vbittype unused1 : 1;
  vbittype AUTOR_ARRET_MOT_DA : 1;
  vbittype EPS_STATE_LKA : 3;
  vbittype STEERWHL_HOLD_BY_DRV : 1;
  vbittype TRQ_LIMIT_STATE : 1;
} _c_IS_DAT_DIRA_Group_msgType;
typedef struct _c_IS_DYN_VOL_GroupBase_msgTypeTag
{
  vbittype ANGLE_VOLANT_1 : 8;
  vbittype ANGLE_VOLANT_0 : 8;
  vbittype VITESSE_ROT_VOL : 8;
  vbittype SENS_ROT_VOL : 1;
  vbittype unused0 : 7;
  vbittype CHKSUM_VOL : 4;
  vbittype CPT_PROCESS_4B_A_VOL : 4;
} _c_IS_DYN_VOL_GroupBase_msgType;
typedef struct _c_IS_DYN_VOL_GroupAdd_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype CODE_DEFAUT_VOL : 4;
  vbittype TRIM_VOL : 1;
  vbittype CALIBRATION_VOL : 1;
  vbittype ETAT_CAPT_VOL : 1;
  vbittype unused1 : 8;
  vbittype VITESSE_ROT_VOL_OPTIMISE : 8;
  vbittype FLG_INIT_AVOL : 1;
  vbittype FLG_AVOL_ICN : 1;
  vbittype ANGLE_VOLANT_ORIGINE : 2;
  vbittype RESERVED : 4;
} _c_IS_DYN_VOL_GroupAdd_msgType;
typedef struct _c_IS_DYN_DAE_Group_msgTypeTag
{
  vbittype CHKSUM_TRME_DYN_DAE : 4;
  vbittype CPT_PROCESS_4B_DAE : 4;
  vbittype CPLE_VOLANT_OPTMSE : 8;
  vbittype unused0 : 1;
  vbittype ETAT_DAE_CPK : 2;
  vbittype CAUSE_DESACTIV_CPK : 3;
  vbittype unused1 : 2;
  vbittype ANGLE_COLONNE_1 : 8;
  vbittype ANGLE_COLONNE_0 : 8;
  vbittype VITESSE_COLONNE_1 : 8;
  vbittype VITESSE_COLONNE_0 : 4;
  vbittype ETAT_DAE_CAV3_VIRTUEL : 3;
  vbittype ETAT_SECU_ANGLE_COL : 1;
} _c_IS_DYN_DAE_Group_msgType;




/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */

#define kETAT_PRINCIP_SEV_DEM                2
#define kETAT_PRINCIP_SEV_Contact            1
#define kETAT_PRINCIP_SEV_Stop               0

#define kETAT_RESEAU_ELEC_TA_SECU            7
#define kETAT_RESEAU_ELEC_TA_DEGRADE         6
#define kETAT_RESEAU_ELEC_TA_NOMINAL         5
#define kETAT_RESEAU_ELEC_REDEMARRAGE        4
#define kETAT_RESEAU_ELEC_DEMARRAGE          3
#define kETAT_RESEAU_ELEC_TI_DISPO_DEM       2
#define kETAT_RESEAU_ELEC_TI_Degrade         1
#define kETAT_RESEAU_ELEC_TI_Nominal         0


#define kETAT_MT_Invalid                     15
#define kETAT_MT_Autonomous_Restart          13
#define kETAT_MT_Autonomous_Starting         10
#define kETAT_MT_Engine_Preparing            7
#define kETAT_MT_Degraded_Restart            6
#define kETAT_MT_Driven_Restart              5
#define kETAT_MT_Stopped                     4
#define kETAT_MT_Engine_Running              3
#define kETAT_MT_Starting                    2
#define kETAT_MT_Cut                         1
#define kETAT_MT_Locked                      0


#define kDIAG_MUX_ON_Enable_SCom_Diagnostics 1
#define kDIAG_MUX_ON_Disable_SCom_Diagnostics 0


#define kVITESSE_VEHICULE_ROUES_Invalid      65535


#define kCODE_DEFAUT_Fault_Code_Exists       1
#define kCODE_DEFAUT_No_Fault_Code           0
#define kETAT_ASSIST_DA_Disability_Parameter 7
#define kETAT_ASSIST_DA_STTd_Assist_Active   4
#define kETAT_ASSIST_DA_STTa_Assist_Active   3
#define kETAT_ASSIST_DA_Dmg_Assist_Active    2
#define kETAT_ASSIST_DA_Nominal_Assist_Active 1
#define kETAT_ASSIST_DA_Assist_Not_Active    0
#define kETAT_LIGNE_APC_Ignition_On          1
#define kETAT_LIGNE_APC_Ignition_Off         0


#define kCPLE_VOLANT_Invalid                 127
#define kETAT_DA_2004_Reserved               3
#define kETAT_DA_2004_Orange_LED             2
#define kETAT_DA_2004_Red_LED                1
#define kETAT_DA_2004_No_Demand              0
#define kETAT_DA_DYN_Invalid                 3
#define kETAT_DA_DYN_Adjustable_Mode         2
#define kETAT_DA_DYN_Dynamic_Mode            1
#define kETAT_DA_DYN_Normal_Mode             0
#define kETAT_DA_2010_Reserved               3
#define kETAT_DA_2010_Orange_LED             2
#define kETAT_DA_2010_Red_LED                1
#define kETAT_DA_2010_No_Demand              0
#define kTRQ_LIMIT_STATE_Saturation_Effective 1
#define kTRQ_LIMIT_STATE_No_Saturation       0
#define kSTEERWHL_HOLD_BY_DRV_Steer_Activity_From_Drv_Trq 1
#define kSTEERWHL_HOLD_BY_DRV_No_Steer_Activity_From_Drv_Trq 0
#define kEPS_STATE_LKA_Defect                4
#define kEPS_STATE_LKA_Active                3
#define kEPS_STATE_LKA_Available             2
#define kEPS_STATE_LKA_Authorised            1
#define kEPS_STATE_LKA_Unauthorised          0
#define kAUTOR_ARRET_MOT_DA_Permission_to_Stop 1
#define kAUTOR_ARRET_MOT_DA_No_Permission_to_Stop 0
#define kDDE_REDEM_DA_Request_Reboot         1
#define kDDE_REDEM_DA_No_Reboot_Required     0


#define kCPLE_VOLANT_OPTMSE_Invalid          127
#define kCAUSE_DESACTIV_CPK_Other_Faults     7
#define kCAUSE_DESACTIV_CPK_EPS_Thermal_Safety_Catch 6
#define kCAUSE_DESACTIV_CPK_Maneuvering_Number_Too_High 5
#define kCAUSE_DESACTIV_CPK_Obstacle_At_Wheel 4
#define kCAUSE_DESACTIV_CPK_Angular_Error_Too_High 3
#define kCAUSE_DESACTIV_CPK_Vehicle_Speed_Too_High 2
#define kCAUSE_DESACTIV_CPK_Driver_Hands_On  1
#define kCAUSE_DESACTIV_CPK_No_Control_Interruption 0
#define kETAT_DAE_CPK_Invalid                3
#define kETAT_DAE_CPK_Control_In_Progress    2
#define kETAT_DAE_CPK_Available              1
#define kETAT_DAE_CPK_Unavailable            0
#define kANGLE_COLONNE_Invalid               32767
#define kVITESSE_COLONNE_Invalid             2047
#define kETAT_SECU_ANGLE_COL_Secure          1
#define kETAT_SECU_ANGLE_COL_Not_Secure      0
#define kETAT_DAE_CAV3_VIRTUEL_Invalid       7
#define kETAT_DAE_CAV3_VIRTUEL_Reserved      6
#define kETAT_DAE_CAV3_VIRTUEL_EPS_Works_with_SelfDet_Offset 5
#define kETAT_DAE_CAV3_VIRTUEL_EPS_Works_with_Calibrated_Offset 4
#define kETAT_DAE_CAV3_VIRTUEL_EPS_Works_with_ESC_Offset 3
#define kETAT_DAE_CAV3_VIRTUEL_Offset_Search_Authorization 2
#define kETAT_DAE_CAV3_VIRTUEL_Offset_Initialization_Request 1
#define kETAT_DAE_CAV3_VIRTUEL_Initialization 0


#define kDownload_Month_December             12
#define kDownload_Month_November             11
#define kDownload_Month_October              10
#define kDownload_Month_September            9
#define kDownload_Month_August               8
#define kDownload_Month_July                 7
#define kDownload_Month_June                 6
#define kDownload_Month_May                  5
#define kDownload_Month_April                4
#define kDownload_Month_March                3
#define kDownload_Month_February             2
#define kDownload_Month_January              1


#define kReq_Mode_DA_Reserved                3
#define kReq_Mode_DA_Adjustable_Mode_Request 2
#define kReq_Mode_DA_Dynamic_Mode_Request    1
#define kReq_Mode_DA_Normal_Mode_Request     0


#define kCONS_ANGLE_CPK_Invalid              32767

#define kDMD_RELAXE_CPK_Invalid              3
#define kDMD_RELAXE_CPK_Relaxe_Request       2
#define kDMD_RELAXE_CPK_No_Request           1
#define kDMD_RELAXE_CPK_Reserved             0

#define kDMD_FCT_CPK_Invalid                 3
#define kDMD_FCT_CPK_SCP9_Control_Request    2
#define kDMD_FCT_CPK_SCP6_Control_Request    1
#define kDMD_FCT_CPK_No_Request              0


#define kANGLE_VOLANT_Invalid                32767
#define kVITESSE_ROT_VOL_Invalid             255
#define kSENS_ROT_VOL_Clockwise              1
#define kSENS_ROT_VOL_Counter_Clockwise      0

#define kETAT_CAPT_VOL_Sensor_Is_Okay        1
#define kETAT_CAPT_VOL_Sensor_Is_Faulty      0
#define kCALIBRATION_VOL_Calibrated          1
#define kCALIBRATION_VOL_Not_Calibrated      0
#define kTRIM_VOL_Trimmed                    1
#define kTRIM_VOL_Not_Trimmed                0
#define kCODE_DEFAUT_VOL_Internal_Failures_by_SWS_ 4
#define kCODE_DEFAUT_VOL_Failure_on_SWS_Angle__RotSpeed_ 3
#define kCODE_DEFAUT_VOL_Failure_on_SWS_Angle 2
#define kCODE_DEFAUT_VOL_Failure_on_SWS_Rotation_Speed_ 1
#define kCODE_DEFAUT_VOL_No_Default___Failure 0
#define kVITESSE_ROT_VOL_OPTIMISE_Invalid    255
#define kANGLE_VOLANT_ORIGINE_Other          3
#define kANGLE_VOLANT_ORIGINE_CAV3           2
#define kANGLE_VOLANT_ORIGINE_Integreated_CAV3 1
#define kANGLE_VOLANT_ORIGINE_Estimator      0
#define kFLG_AVOL_ICN_Uncertain_yet_Valid_Value 1
#define kFLG_AVOL_ICN_Valid_Value_in_Range   0
#define kFLG_INIT_AVOL_Steering_Wheel_Angle_Memorized 1
#define kFLG_INIT_AVOL_Steering_Wheel_Angle_Available 0


#define kDMD_DELEST_DA_Power_Cut_Request     1
#define kDMD_DELEST_DA_Not_Requested         0

#define kLKA_STATE_Reserved                  7
#define kLKA_STATE_Collision                 6
#define kLKA_STATE_Defect                    5
#define kLKA_STATE_Active                    4
#define kLKA_STATE_Authorized                3
#define kLKA_STATE_Selected                  2
#define kLKA_STATE_Unselected                1
#define kLKA_STATE_Unavailable               0

#define kLXA_ACTIVATION_LPA_Function         1
#define kLXA_ACTIVATION_LKA_Function         0

#define kLKA_TRQ_FACT_REQ_Invalid            127
#define kLKA_TRQ_FACT_REQ_Unavailable        126


#define kEFFAC_DEFAULT_DIAG_Default_Memory_Erase 1
#define kEFFAC_DEFAULT_DIAG_No_Specific_Action 0

#define kMODE_DIAG_Operation_and_Comm_Inhibited 1
#define kMODE_DIAG_No_Particular_Operation   0

#define kDIAG_INTEGRA_ELEC_No_Frame_Transmission 1
#define kDIAG_INTEGRA_ELEC_No_Particular_Operation 0


#define kVITESSE_VEHICLE_BV_Invalid          65535


#define kDTC_State_Current                   1
#define kDTC_State_History                   0


#define kRegul_ABR_Active_Regulation         1
#define kRegul_ABR_No_Regulation             0


#define kAccel_Lat_Invalid                   32767


#define kREQ_Lampe_DEF_ESP_Request_On        1
#define kREQ_Lampe_DEF_ESP_No_Request        0

#define kRegul_ESP_Active_Regulation         1
#define kRegul_ESP_No_Regulation             0

#define kESP_Deconnecte_Disconnected         1
#define kESP_Deconnecte_Connected            0


#define kOFFSET_Unavailable                  32766
#define kOFFSET_Invalid                      32767

#define kACQ_INTERRUPT_DAE_Acknowledge       1
#define kACQ_INTERRUPT_DAE_No_Acknowledge    0

#define kPRECISION_OFFSET_Invalid            31
#define kPRECISION_OFFSET_Unavailable        30


#define kCONFIG_VHL_INVALID                  7
#define kCONFIG_VHL_SHOW_ROOM                6
#define kCONFIG_VHL_APV                      5
#define kCONFIG_VHL_CLIENT                   4
#define kCONFIG_VHL_STORAGE___TRANSPORT      3
#define kCONFIG_VHL_CHECK                    2
#define kCONFIG_VHL_PLANT                    1
#define kCONFIG_VHL_FITTING                  0




/* -----------------------------------------------------------------------------
    &&&~ Message Unions
 ----------------------------------------------------------------------------- */

typedef union _c_IS_DAT_BSI_432_bufTag
{
  vuint8 _c[8];
  _c_IS_DAT_BSI_432_msgType IS_DAT_BSI_432;
} _c_IS_DAT_BSI_432_buf;
typedef union _c_IS_DYN2_CMM_348_bufTag
{
  vuint8 _c[6];
  _c_IS_DYN2_CMM_348_msgType IS_DYN2_CMM_348;
} _c_IS_DYN2_CMM_348_buf;
typedef union _c_IS_DYN_CMM_208_bufTag
{
  vuint8 _c[5];
  _c_IS_DYN_CMM_208_msgType IS_DYN_CMM_208;
} _c_IS_DYN_CMM_208_buf;
typedef union _c_IS_DYN_ABR_bufTag
{
  vuint8 _c[6];
  _c_IS_DYN_ABR_msgType IS_DYN_ABR;
} _c_IS_DYN_ABR_buf;
typedef union _c_IS_SUPV_DIRA_bufTag
{
  vuint8 _c[6];
  _c_IS_SUPV_DIRA_msgType IS_SUPV_DIRA;
  _c_IS_SUPV_DIRA_IS_SUPV_DIRA_Group_msgType IS_SUPV_DIRA_IS_SUPV_DIRA_Group;
} _c_IS_SUPV_DIRA_buf;
typedef union _c_IS_DAT_DIRA_bufTag
{
  vuint8 _c[4];
  _c_IS_DAT_DIRA_msgType IS_DAT_DIRA;
  _c_IS_DAT_DIRA_IS_DAT_DIRA_Group_msgType IS_DAT_DIRA_IS_DAT_DIRA_Group;
} _c_IS_DAT_DIRA_buf;
typedef union _c_IS_DYN_DAE_bufTag
{
  vuint8 _c[7];
  _c_IS_DYN_DAE_msgType IS_DYN_DAE;
  _c_IS_DYN_DAE_IS_DYN_DAE_Group_msgType IS_DYN_DAE_IS_DYN_DAE_Group;
} _c_IS_DYN_DAE_buf;
typedef union _c_IS_VERS_DIRA_115_bufTag
{
  vuint8 _c[8];
  _c_IS_VERS_DIRA_115_msgType IS_VERS_DIRA_115;
} _c_IS_VERS_DIRA_115_buf;
typedef union _c_IS_RES_DIAG_ON_CAN_bufTag
{
  vuint8 _c[8];
  _c_IS_RES_DIAG_ON_CAN_msgType IS_RES_DIAG_ON_CAN;
} _c_IS_RES_DIAG_ON_CAN_buf;
typedef union _c_XCP_RES_bufTag
{
  vuint8 _c[8];
  _c_XCP_RES_msgType XCP_RES;
} _c_XCP_RES_buf;
typedef union _c_XCP_REQ_bufTag
{
  vuint8 _c[8];
  _c_XCP_REQ_msgType XCP_REQ;
} _c_XCP_REQ_buf;
typedef union _c_IS_DAT_BSI_412_bufTag
{
  vuint8 _c[4];
  _c_IS_DAT_BSI_412_msgType IS_DAT_BSI_412;
} _c_IS_DAT_BSI_412_buf;
typedef union _c_IS_DYN_AAS_bufTag
{
  vuint8 _c[4];
  _c_IS_DYN_AAS_msgType IS_DYN_AAS;
} _c_IS_DYN_AAS_buf;
typedef union _c_IS_DYN_VOL_bufTag
{
  vuint8 _c[7];
  _c_IS_DYN_VOL_msgType IS_DYN_VOL;
  _c_IS_DYN_VOL_IS_DYN_VOL_GroupBase_msgType IS_DYN_VOL_IS_DYN_VOL_GroupBase;
  _c_IS_DYN_VOL_IS_DYN_VOL_GroupAdd_msgType IS_DYN_VOL_IS_DYN_VOL_GroupAdd;
} _c_IS_DYN_VOL_buf;
typedef union _c_IS_DAT4_V2_BSI_552_bufTag
{
  vuint8 _c[8];
  _c_IS_DAT4_V2_BSI_552_msgType IS_DAT4_V2_BSI_552;
} _c_IS_DAT4_V2_BSI_552_buf;
typedef union _c_IS_DAT_BSI_3F2_bufTag
{
  vuint8 _c[8];
  _c_IS_DAT_BSI_3F2_msgType IS_DAT_BSI_3F2;
} _c_IS_DAT_BSI_3F2_buf;
typedef union _c_IS_INTE_ELECTRON_BSI_bufTag
{
  vuint8 _c[1];
  _c_IS_INTE_ELECTRON_BSI_msgType IS_INTE_ELECTRON_BSI;
} _c_IS_INTE_ELECTRON_BSI_buf;
typedef union _c_IS_DYN_CMM_388_bufTag
{
  vuint8 _c[2];
  _c_IS_DYN_CMM_388_msgType IS_DYN_CMM_388;
} _c_IS_DYN_CMM_388_buf;
typedef union _c_IS_ACQ_NEW_JDD_55F_bufTag
{
  vuint8 _c[1];
  _c_IS_ACQ_NEW_JDD_55F_msgType IS_ACQ_NEW_JDD_55F;
} _c_IS_ACQ_NEW_JDD_55F_buf;
typedef union _c_IS_EMIS_NEW_JDD_CAN_DIRA_bufTag
{
  vuint8 _c[8];
  _c_IS_EMIS_NEW_JDD_CAN_DIRA_msgType IS_EMIS_NEW_JDD_CAN_DIRA;
} _c_IS_EMIS_NEW_JDD_CAN_DIRA_buf;
typedef union _c_IS_ACQ_JDD_CAN_BSI_772_bufTag
{
  vuint8 _c[1];
  _c_IS_ACQ_JDD_CAN_BSI_772_msgType IS_ACQ_JDD_CAN_BSI_772;
} _c_IS_ACQ_JDD_CAN_BSI_772_buf;
typedef union _c_IS_DAT_ABR_50D_bufTag
{
  vuint8 _c[1];
  _c_IS_DAT_ABR_50D_msgType IS_DAT_ABR_50D;
} _c_IS_DAT_ABR_50D_buf;
typedef union _c_IS_DYN2_FRE_3CD_bufTag
{
  vuint8 _c[2];
  _c_IS_DYN2_FRE_3CD_msgType IS_DYN2_FRE_3CD;
} _c_IS_DYN2_FRE_3CD_buf;
typedef union _c_IS_DYN_CDS_34D_bufTag
{
  vuint8 _c[1];
  _c_IS_DYN_CDS_34D_msgType IS_DYN_CDS_34D;
} _c_IS_DYN_CDS_34D_buf;
typedef union _c_PROTO_HS1_DYN_UCF_5CD_bufTag
{
  vuint8 _c[4];
  _c_PROTO_HS1_DYN_UCF_5CD_msgType PROTO_HS1_DYN_UCF_5CD;
} _c_PROTO_HS1_DYN_UCF_5CD_buf;
typedef union _c_IS_DAT_BSI_572_bufTag
{
  vuint8 _c[2];
  _c_IS_DAT_BSI_572_msgType IS_DAT_BSI_572;
} _c_IS_DAT_BSI_572_buf;
/* -----------------------------------------------------------------------------
    &&&~ Signal Unions for group signals
 ----------------------------------------------------------------------------- */

typedef union _c_IS_SUPV_DIRA_Group_bufTag
{
  vuint8 _c[6];
  _c_IS_SUPV_DIRA_Group_msgType IS_SUPV_DIRA_Group;
} _c_IS_SUPV_DIRA_Group_buf;
typedef union _c_IS_DAT_DIRA_Group_bufTag
{
  vuint8 _c[3];
  _c_IS_DAT_DIRA_Group_msgType IS_DAT_DIRA_Group;
} _c_IS_DAT_DIRA_Group_buf;
typedef union _c_IS_DYN_VOL_GroupBase_bufTag
{
  vuint8 _c[5];
  _c_IS_DYN_VOL_GroupBase_msgType IS_DYN_VOL_GroupBase;
} _c_IS_DYN_VOL_GroupBase_buf;
typedef union _c_IS_DYN_VOL_GroupAdd_bufTag
{
  vuint8 _c[4];
  _c_IS_DYN_VOL_GroupAdd_msgType IS_DYN_VOL_GroupAdd;
} _c_IS_DYN_VOL_GroupAdd_buf;
typedef union _c_IS_DYN_DAE_Group_bufTag
{
  vuint8 _c[7];
  _c_IS_DYN_DAE_Group_msgType IS_DYN_DAE_Group;
} _c_IS_DYN_DAE_Group_buf;




/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_BSI_432_buf V_MEMRAM2 IS_DAT_BSI_432;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN2_CMM_348_buf V_MEMRAM2 IS_DYN2_CMM_348;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_CMM_208_buf V_MEMRAM2 IS_DYN_CMM_208;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_ABR_buf V_MEMRAM2 IS_DYN_ABR;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_SUPV_DIRA_buf V_MEMRAM2 IS_SUPV_DIRA;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_DIRA_buf V_MEMRAM2 IS_DAT_DIRA;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_DAE_buf V_MEMRAM2 IS_DYN_DAE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_VERS_DIRA_115_buf V_MEMRAM2 IS_VERS_DIRA_115;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_RES_DIAG_ON_CAN_buf V_MEMRAM2 IS_RES_DIAG_ON_CAN;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_XCP_RES_buf V_MEMRAM2 XCP_RES;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_XCP_REQ_buf V_MEMRAM2 XCP_REQ;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_BSI_412_buf V_MEMRAM2 IS_DAT_BSI_412;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_AAS_buf V_MEMRAM2 IS_DYN_AAS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_VOL_buf V_MEMRAM2 IS_DYN_VOL;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT4_V2_BSI_552_buf V_MEMRAM2 IS_DAT4_V2_BSI_552;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_BSI_3F2_buf V_MEMRAM2 IS_DAT_BSI_3F2;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_INTE_ELECTRON_BSI_buf V_MEMRAM2 IS_INTE_ELECTRON_BSI;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_CMM_388_buf V_MEMRAM2 IS_DYN_CMM_388;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_ACQ_NEW_JDD_55F_buf V_MEMRAM2 IS_ACQ_NEW_JDD_55F;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_EMIS_NEW_JDD_CAN_DIRA_buf V_MEMRAM2 IS_EMIS_NEW_JDD_CAN_DIRA;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_ACQ_JDD_CAN_BSI_772_buf V_MEMRAM2 IS_ACQ_JDD_CAN_BSI_772;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_ABR_50D_buf V_MEMRAM2 IS_DAT_ABR_50D;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN2_FRE_3CD_buf V_MEMRAM2 IS_DYN2_FRE_3CD;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_CDS_34D_buf V_MEMRAM2 IS_DYN_CDS_34D;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PROTO_HS1_DYN_UCF_5CD_buf V_MEMRAM2 PROTO_HS1_DYN_UCF_5CD;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_BSI_572_buf V_MEMRAM2 IS_DAT_BSI_572;
/* RAM CATEGORY 2 END */

/* -----------------------------------------------------------------------------
    &&&~ Extern decl for message buffer for group signals
 ----------------------------------------------------------------------------- */

V_MEMRAM0 extern  V_MEMRAM1 _c_IS_SUPV_DIRA_Group_buf V_MEMRAM2 IS_SUPV_DIRA_Group;
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DAT_DIRA_Group_buf V_MEMRAM2 IS_DAT_DIRA_Group;
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_VOL_GroupBase_buf V_MEMRAM2 IS_DYN_VOL_GroupBase;
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_VOL_GroupAdd_buf V_MEMRAM2 IS_DYN_VOL_GroupAdd;
V_MEMRAM0 extern  V_MEMRAM1 _c_IS_DYN_DAE_Group_buf V_MEMRAM2 IS_DYN_DAE_Group;






/* disable magic number check for support of multiple projects */
#ifndef SKIP_MAGIC_NUMBER
#define SKIP_MAGIC_NUMBER
#endif

#include "drv_par_1.h"


#endif /* __DRV_PAR_H__ */
