/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2009 by Vctr Informatik GmbH.                                              All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vctr Informatik GmbH.
 *                Vctr Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vctr Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  Gpt_PBcfg.c
 *    Component:  DrvGpt_Tms570Tirti01Asr
 *       Module:  DrvGpt
 *    Generator:  Davinci Configurator
 *
 *  Description:  This module implements a driver to provide services for starting and stopping a functional timer
 *                instance (channel) within the hardware timer module. Individual timeout periods (single shot mode) as
 *                well as repeating timeout periods (continuous mode) can be generated. The user can configure, if a
 *                notification shall be invoked, when the requested timeout period has expired. Notifications can be
 *                enabled and disabled at runtime. Both, the relative time elapsed since the last notification occurred
 *                (respectively the channel has been started) and the time remaining until the next notification will
 *                occur, can be queried. The GPT Driver can be used to wakeup the ECU, whenever a predefined timeout
 *                period has expired. A mode switching service is provided to switch the GPT Driver between normal
 *                operation and sleep mode.
 *********************************************************************************************************************/

/**********************************************************************************************************************
  
    Project:    EPS.ecuc
    Generated:  2014-01-31 04:28 pm
    Licensee:   Vector AUTOSAR Basic Software (MICROSAR)
 
    This file is generated by DaVinci Configurator Base - DAVINCICFG.EXE V4.0.67.0.
    Do not modify this file, otherwise the software may behave in unexpected way.
    
 *********************************************************************************************************************/

/* ---- Module switch ---------------------------------------------------------------------------------------------- */
#define GPT_CFG

/* ---- Includes --------------------------------------------------------------------------------------------------- */
#include "Std_Types.h"

/* ---- Module Header Includes ------------------------------------------------------------------------------------- */
#include "Gpt.h"

/* ---- Perform version checking ----------------------------------------------------------------------------------- */
#if (   (GPT_SW_MAJOR_VERSION != (1)) \
     || (GPT_SW_MINOR_VERSION != (0)))
  #error "Version numbers of Gpt_PBcfg.c and Gpt.h are inconsistent!"
#endif

#if (   (GPT_CFG_MAJOR_VERSION != (1)) \
     || (GPT_CFG_MINOR_VERSION != (0)))
  #error "Version numbers of Gpt_PBcfg.c and Gpt_Cfg.h are inconsistent!"
#endif

/* --- CFG defines for Post Build configuration -------------------------------------------------------------------- */
/*------------------------------------------------------------------------------------------------------------------ */
/*---- CFG Constants for Post Build configuration ------------------------------------------------------------------ */
/*------------------------------------------------------------------------------------------------------------------ */

#define GPT_START_SEC_PBCFG
#include "MemMap.h"

/*<GPT_CHANNEL_CONFIG>*/
const Gpt_ChannelConfigType Gpt_Runtime_Chl_at[] =/* PRQA S 3408 *//* MISRA-C:2004 Rules applicable to message 3408: Struct only accessed by a separate sturcture which is external known*/ 
{
     {
        /* user configuration for SystemTime_uS */
        SystemTick,/* Channel Nofitication */
        79,/* Prescale Value */
        /* WakeupSourceID */
        0,/* Wakeup SourceID */
        0,/* Channel Clock Source */
        GPT_MODE_CONTINUOUS,/* Channel Mode */
        0x00/* Hardware Channel */
    }
};
/*</GPT_CHANNEL_CONFIG>*/

#define GPT_STOP_SEC_PBCFG
#include "MemMap.h"  /* PRQA S 5087 *//* MD_MSR_3.4  */

#define GPT_START_SEC_PBCFG_ROOT
#include "MemMap.h"  /* PRQA S 5087 *//* MD_MSR_3.4  */

/* global runtime configuration structure */
/*<GPT_CONFIGURATION>*/
const Gpt_ConfigType Gpt_Runtime =
{
    Gpt_Runtime_Chl_at,    /*Pointer to Channel Config*/
    1    /*Number of Channels*/
};
    
/*</GPT_CONFIGURATION>*/

/* Prescale factors per counter block */
#define GPT_CHANNEL_PRESCALE_CLK0   /*<GPT_CHANNEL_PRESCALE_CLK0/>*/ (0x4Fu)
#define GPT_CHANNEL_PRESCALE_CLK1   /*<GPT_CHANNEL_PRESCALE_CLK1/>*/ (0x4Fu)

#define GPT_STOP_SEC_PBCFG_ROOT
#include "MemMap.h"  /* PRQA S 5087 *//* MD_MSR_3.4  */

/*----- End of File --------------------------------------------------------*/
