/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2010 by Vctr Informatik GmbH.                                              All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vctr Informatik GmbH.
 *                Vctr Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vctr Informatik GmbH.
 *  \endverbatim
 *  ===================================================================================================================
 *  FILE DESCRIPTION
 *  ===================================================================================================================
 *         File:  IoHwAb_Cfg.h
 *    Component:  EcuAb_AsrIoHwAb
 *       Module:  IoHwAb
 *    Generator:  -
 *
 *  Description:  This file contains the contains the configuration parameters of the IO Hardware Abstraction.
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
    Project:       EPS.ecuc
    Generated:  2014-01-31 04:28 pm
    Licensee:    Vector AUTOSAR Basic Software (MICROSAR)
 
    This file is generated by DaVinci Configurator Base - DAVINCICFG.EXE V4.0.67.0.
    Do not modify this file, otherwise the software may behave in unexpected way.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  ===================================================================================================================
 *  Name                          Initials      Company
 *  ===================================================================================================================
 *  Christian Marchl              Chm           Vctr Informatik GmbH
 *  Christoph Ederer              Cer           Vctr Informatik GmbH
 *  ===================================================================================================================
 *  REVISION HISTORY
 *  ===================================================================================================================
 *  Version   Date        Author  Change Id     Description
 *  ===================================================================================================================
 *  1.01.01   2007-11-26  Chm     ESCAN00022772 No changes here
 *                                ESCAN00023310 Changed line ending to CRLF
 *                                -             New file header added.
 *  1.01.02   2007-02-13  Chm     ESCAN00024551 GenRule G11 affected: replaced ON with STD_ON (in condition)
 *                                -             Function GenRules changed for more readability.
 *  1.02.00   2008-05-07  Cer     5006330       Created BSWMD, reworked transformation to use ECU-C file as input,
 *                                              multiple operations in one user defined port possible now, DCM
 *                                              interface added
 *  1.02.01   2008-06-13  Cer     ESCAN00027572 Rework of identifiers in Generation.xml and Validation.xml for
 *                                              EAD versions 3.2.4.341 and later, Indexes of EAD function
 *                                              RefValue() adjusted
 *  1.02.02   2008-07-10  Cer     ESCAN00028289 Read functions available for all signals now.
 *                                ESCAN00027419 Tags removed
 *                                ESCAN00026634 SIP check added
 *  1.02.03   2008-08-21  Cer     ESCAN00028337 View.xml added to Schemes
 *                                ESCAN00029093 Error in Transformation of SWC-structure reworked
 *                                ESCAN00028340 Critical section handling added
 *            2008-09-09  Chm     ESCAN00029855 Generation of references corrected
 *                                ESCAN00029854 Version defines corrected
 *                                ESCAN00029853 Corrected critical section handling
 *  1.03.00   2008-10-02  Cer     ESCAN00030019 Shortname adapted to AUTOSAR specification
 *                                ESCAN00029653 SWC generation for float data types reworked
 *  1.04.00   2008-12-05  Cer     -             Include of 'Rte_Type.h'/'IoHwAb_Types.h' moved from implementation
 *                                              to configuration header
 *                        Chm     ESCAN00031178 Added parameter IoHwAbstractionRequirementId
 *                        Chm     ESCAN00030122 Removed automatic definition of configuration container.
 *                        Chm     ESCAN00032103 Changed critical section handling to be independent of Board
 *                                              InterruptFunctionSet parameter if SchM is used.
 *  1.05.00   2008-12-19  Cer     ESCAN00032205 SubFunction 'ResetToDefault' added to DCM interface, Configuration of
 *                                              default value added to signal configuration
 *  1.05.01   2009-02-24  Cer     ESCAN00031178 RequirementId added to GUI
 *  1.05.02   2009-03-16  Cer     ESCAN00029642 Sortability added for all the tables in the view (IoHwAb.xml)
 *                                ESCAN00032636 Multiplicity of container IoHwAbDiscrete reworked (no discrete
 *                                              signal is created on startup anymore; Identifier.xml)
 *                                ESCAN00032636 Multiplicity of container IoHwAbDiscrete reworked (no discrete
 *                                              signal is created on startup anymore; Identifier.xml)
 *                                ESCAN00032763 Dev-Error Detection is disabled by default (Identifier.xml)
 *                                ESCAN00033386 RTE includes moved from configuration header to C-files
 *                                ESCAN00033387 Added support for generation of service ports (Identifer.xml,
 *                                              SWC_IoHwAb.xsl)
 *                                ESCAN00033645 Generation of data types of IOHWAB-specific default-values fixed
 *                                              (GenIoHwAbUserSourceTemplate.xml)
 *                                ESCAN00033835 Added ADMIN-DATA to SWC generation (SWC_IoHwAb.xsl)
 *  1.06.00   2009-07-10  Cer     ESCAN00034782 Added update of CalSourceType to avoid generation of empty DIO
 *                                              entity identifiers
 *                                ESCAN00036329 Fixed icon placement in view
 *                                ESCAN00036279 Automatic generation of SWC file added
 *                                ESCAN00032561 User blocks added to IoHwAb.c to avoid overwriting of user
 *                                              modifications in the generated template
 *                                ESCAN00029651 Added informative text about all the configured CAL entities
 *                                              to IoHwAb.c
 *                                ESCAN00036542 Added include of IoHwAbstraction types to the DCM header file
 *                                ESCAN00029887 Added dummy-statement mechanism to prevent compile warnings
 *  1.06.01   2009-09-22  Cer     ESCAN00037605 Reworked DCM services to provide multiple writing to the DCM
 *                                ESCAN00037601 Functionality of DCM sub-function 'resetToDefault' corrected
 *                                ESCAN00038188 Validation of default values extended to input signals
 *  1.06.02   2010-04-28  Cer     ESCAN00040647 Added general implementation are for local functions (IoHwAb.c)
 *                                ESCAN00040708 Reworked setting of parameter IoHwAbCalSourceType to ensure, that
 *                                              generation works correctly, even if the project is not saved
 *                                ESCAN00042720 'AS'-tag added to all identifers in Identifer.xml due to an in-
 *                                              compatibility with DaVinci Configurator from version 4.00.40
 *  1.06.03   2010-11-25  Cer     ESCAN00046423 Optional generation of symbolic name prefixes added
 *                                ESCAN00044073 Renamed 'Insert' buttons in the GUI to 'Append'
 *                                ESCAN00043885 Renamed control 'Component Name' and reworked description
 *                                ESCAN00043745 Default value selection removed from DIO entity parameter
 *                                -             Removed all unnecessary information from Identifer.xml (Labels, ...)
 *********************************************************************************************************************/

/* Do not modify the following parts. */
/* Modification is only allowed in the described parts */

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/

/*<IOHWAB_HEADER_INCLUDE>*/

/* RTE Includes: Function prototypes and  types */
#include "Rte_Type.h"
/*</IOHWAB_HEADER_INCLUDE>*/

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/

/* switch between public and private sections ------------------------------*/
#if (!defined IOHWAB_CFG_H_PUBLIC)

#define IOHWAB_CFG_H_PUBLIC
/*---- Version identification - satisfies [BSW0003] ------------------------*/
#define IOHWAB_CFG_MAJOR_VERSION    (1u)
#define IOHWAB_CFG_MINOR_VERSION    (6u)
#define IOHWAB_CFG_PATCH_VERSION    (3u)


/* ---- API relevant (public) section of configuration ---------------------*/
/* ---- pre-compile switches for services ----------------------------------*/
#define IOHWAB_VERSION_INFO_API       /*<IOHWAB_VERSION_INFO_API/>*/ (STD_ON)
#define IOHWAB_DEV_ERROR_DETECT       /*<IOHWAB_DEV_ERROR_DETECT/>*/ (STD_ON)
#define IOHWAB_USE_INIT_FUNCTION      /*<IOHWAB_USE_INIT_FUNCTION/>*/ (STD_OFF)
/* ------------------------------------------------------------------------ */
/*              Configurations for Development mode                         */
#if (STD_ON == IOHWAB_DEV_ERROR_DETECT)     /* [IoHwAb108] Check parameters */
/* ------------------------------------------------------------------------ */

    #define IOHWAB_CFG_CHK_PARAM_PTR   /*<IOHWAB_CFG_CHK_PARAM_PTR/>*/ (STD_ON)
    #define IoHwAb_Errorhook(IoHwAb_FunctionId, IoHwAb_ErrorCode) \
        /*<IOHWAB_ERRORHOOK>*/(Det_ReportError((IOHWAB_MODULE_ID), (0u), (IoHwAb_FunctionId), (IoHwAb_ErrorCode)))/*</IOHWAB_ERRORHOOK>*/

/* ------------------------------------------------------------------------ */
/*                  Configurations for Production mode                      */
#else
/* ------------------------------------------------------------------------ */

    #define IOHWAB_CFG_CHK_PARAM_PTR    (STD_OFF)

/* ------------------------------------------------------------------------ */
#endif   /* End of switch between development / production mode */
/* ------------------------------------------------------------------------ */

/**********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 *********************************************************************************************************************/
/*<IOHWAB_CFG_CALPROTOTYPES>*/
/* Prototypes of CalSignal services can be found in Rte_IoHwAbstraction.h */
/*</IOHWAB_CFG_CALPROTOTYPES>*/

/*<IOHWAB_CFG_USERDEFPROTOTYPES>*/
/* Prototypes of UserDefSignal services can be found in Rte_IoHwAbstraction.h */
/*</IOHWAB_CFG_USERDEFPROTOTYPES>*/

/*<IOHWAB_CFG_HANDLERPROTOTYPES>*/
/* Prototypes of signal handlers can be found in Rte_IoHwAbstraction.h */
/*</IOHWAB_CFG_HANDLERPROTOTYPES>*/

#endif /* Public part: #if (!defined IOHWAB_CFG_H_PUBLIC) */

/*---- Module relavant configurations (private, C file only) ---------------*/
#if ((defined IOHWAB_SOURCE) || (defined IOHWAB_DIO_SOURCE))

/*---- CFG Includes --------------------------------------------------------*/
/*<IOHWAB_CFG_INCLUDE_DET>*/
#include "Det.h"
/*</IOHWAB_CFG_INCLUDE_DET>*/

/*<IOHWAB_INCLUDE_LIST>*/
#include "Dio.h"
/*</IOHWAB_INCLUDE_LIST>*/

/*<IOHWAB_INCLUDE_IRQ>*/
#include "SchM_IoHwAb.h"
/*</IOHWAB_INCLUDE_IRQ>*/
/*---- include of supporting definitions for configuration -----------------*/

#define IoHwAb_GlobalSuspend() /*<IOHWAB_CFG_GLOBAL_SUSPEND/>*/ SchM_Enter_IoHwAb(IOHWAB_EXCLUSIVE_AREA_0)
#define IoHwAb_GlobalRestore() /*<IOHWAB_CFG_GLOBAL_RESTORE/>*/ SchM_Exit_IoHwAb(IOHWAB_EXCLUSIVE_AREA_0)

#endif /* #if ((defined IOHWAB_SOURCE) || (defined IOHWAB_DIO_SOURCE)) */
/**********************************************************************************************************************
 *  END OF FILE: IoHwAb_Cfg.h
 *********************************************************************************************************************/

