/* -----------------------------------------------------------------------------
  Filename:    v_par_1.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyVcfgNameDecorator
               
               Configuration   : C:\SynergyProjects\PSA_BMPV_EPS_TMS570-nzx5jd\PSA_BMPV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U

  Generated by , 2014-02-25  15:59:02
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__V_PAR_1_H__)
#define __V_PAR_1_H__

/* -----------------------------------------------------------------------------
    &&&~ BaseEnv_PHF_Includes
 ----------------------------------------------------------------------------- */

#include "v_cfg.h"
#include "v_def.h"


/* -----------------------------------------------------------------------------
    &&&~ GENy Version Information
 ----------------------------------------------------------------------------- */

#define VGEN_DELIVERY_VERSION_BYTE_0_1       0x11
#define VGEN_DELIVERY_VERSION_BYTE_1_1       0x08
#define VGEN_DELIVERY_VERSION_BYTE_2_1       0x02
#define VGEN_DELIVERY_VERSION_BYTE_3_1       0x01
#define VGEN_DELIVERY_VERSION_BYTE_4_1       0x30
#define VGEN_DELIVERY_VERSION_BYTE_5_1       0x01
#define VGEN_DELIVERY_VERSION_BYTE_6_1       0x24
#define VGEN_DELIVERY_VERSION_BYTE_7_1       0x00
#define VGEN_DELIVERY_VERSION_BYTE_8_1       0x00
#define VGEN_DELIVERY_VERSION_BYTE_9_1       0x00
#define kGENyVersionNumberOfBytes_1          10
/* ROM CATEGORY 4 START */
V_MEMROM0 extern  V_MEMROM1 vuint8 V_MEMROM2 kGENyVersion_1[kGENyVersionNumberOfBytes_1];
/* ROM CATEGORY 4 END */




#endif /* __V_PAR_1_H__ */
