/* -----------------------------------------------------------------------------
  Filename:    Det_Cfg.h
  Description: Toolversion: 10.01.07.01.01.01.22.00.00.00
               
               Serial Number: CBD1010122
               Customer Info: Nxtr
                              GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments
               
               
               Generator Fwk   : GENy 
               Generator Module: Det
               
               Configuration   : D:\usr\usage\Delivery\CBD10x\CBD1010122\internal\TsiStandard\Config\TsiStandard_ecuc.arxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66

  Generated by , 2010-12-15  17:00:50
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DET_CFG_H)
#define DET_CFG_H

#define DET_ENABLED
#define DETDLL_VERSION                       0x0107
#define DETDLL_RELEASE_VERSION               0x00
#define DET_VERSION_INFO_API                 STD_ON
#define DET_DEBUG_ENABLED
#define DET_GLOBALFILTERSIZE                 1
#define DET_BREAKFILTERSIZE                  1
#define DET_LOGBUFFERSIZE                    0
#define DET_ENTRY_CALLOUT_DISABLED

/* begin Fileversion check */

/* end Fileversion check */

#endif /* DET_CFG_H */
