/* The following is only part of the header that was required at the 
 * time this component was made. 
 */
#ifndef NVM_CFG_H
#define NVM_CFG_H

/*<NVM_BLOCK_ID_CFG>*/
#define Rte_NvmBlock_MtrPos_MtrPosSnsr_EOLData (1U)
#define Rte_NvmBlock_MtrPosSnsrLearning_MtrSnsrLrnParam (1U)
#define Rte_NvmBlock_MtrCurr_ShCurrCal (1U)
#define Rte_NvmBlock_HwTrq_HwTrqScaleData (1U)
#define Rte_NvmBlock_Polarity_EOLCtrlPolarity (1U)
#define Rte_NvmBlock_HwTrq_HwTrqTrimData (1U)
#define Rte_NvmBlock_DiagMgr_NTCStrgArray (1U)
#define Rte_NvmBlock_LrnEOT_LearnedEOT (1U)
#define Rte_NvmBlock_SrlComInput_SrlComWIRFltStatus_Cnt_u16 (1U)
#define NVM_BLOCK_CUSTWIRSELECT (1U)
#define NVM_BLOCK_HWDESCDATA (1U)
#define Deprecated2_NVM_BLOCK_PRTNUMBER (1U)
#define NVM_BLOCK_EPSDEFEATS (1U)
#define NvM_NVM_BLOCK_DEM (1U)
#define Rte_NvmBlock_DigHwTrq_DigTrqScale (1U)
#define Rte_NvmBlock_DigHwTrq_DigTrqTrim (1U)
#define Rte_NvmBlock_StaMd_TypeHRamBuffer (1U)
#define Rte_NvmBlock_ParamComp_EOLNomMtrParam (1U)
#define Rte_NvmBlock_Return_EOLRtnRange (1U)
#define Rte_NvmBlock_TrqCmdScl_TorqueCmdSF_Uls_f32 (1U)
#define Rte_NvmBlock_LrnEOT_RackCntrPerf (1U)
#define Deprecated_NvmBlock_MtrTrqLmt_EOLTrqCmdSclFac_Uls_u7p9 (1U)
#define Deprecated_NVM_BLOCK_PRTNUMBER (1U)
#define NVM_BLOCK_SER_CALPRGFLAG (1U)
#define NVM_BLOCK_SER_VINDATA (1U)
#define NVM_BLOCK_SER_SYSTEMNAME (1U)
#define NVM_BLOCK_SER_REPAIRSHOPCODE (1U)
#define NVM_BLOCK_SER_PROGDATE (1U)
#define NVM_BLOCK_SER_SYSVERSCODEDDI (1U)
#define NVM_BLOCK_SER_CUSTMEC (1U)
#define NVM_BLOCK_SER_GMMANFDATA (1U)
#define NVM_BLOCK_SER_MANFTRAC (1U)
#define NVM_BLOCK_SER_ENDMODELPN (1U)
#define NVM_BLOCK_SER_ENDMODELPNAC (1U)
#define NVM_BLOCK_CMS_NXTRMEC (1U)
#define NVM_BLOCK_CMS_NXTRMECFLAG (1U)
#define NVM_BLOCK_CMS_ECUSRLNUM (1U)
#define NVM_BLOCK_CMS_EPSSRLNUM (1U)
#define NVM_BLOCK_CMS_ECUHWPN (1U)
#define NVM_BLOCK_CMS_NXTRMANUFSCRATCHPAD (1U)
#define NVM_BLOCK_CMS_IGNCNTR (1U)
#define NVM_BLOCK_SER_GEARCFACTOR (1U)
#define NVM_BLOCK_SER_GEARSRLNUM (1U)
#define NVM_BLOCK_SER_SEED (1U)
#define NVM_BLOCK_SER_KEY (1U)
#define NVM_BLOCK_SER_ECUCONFIGDATA (1U)
#define NVM_BLOCK_NXTRWIRSELECT (1U)

#endif /* NVM_CFG_H */
