/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *  Copyright (c) 2006-2009 by Vctr Informatik GmbH, all rights reserved
 *
 *  Please note, that this file contains example configuration used by the ECUM. This code may influence the
 *  behavior of the ECUM in principle. Therefore, great care must be taken to verify the correctness of the
 *  implementation.
 *
 *  The contents of the originally delivered files are only examples resp. implementation proposals. With regard to the
 *  fact that these functions are meant for demonstration purposes only, Vctr Informatik's liability shall be
 *  expressly excluded in cases of ordinary negligence, to the extent admissible by law or statute.
 *
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  EcuM_Callout_Stubs.c
 *    Component:  SysService_AsrEcuM
 *       Module:  EcuM
 *    Generator:  EAD
 *
 *  Description:  The ECU State Manager is responsible for
 *                  - initialization of the entire BSW Modules (including OS and RTE
 *                  - configuration of the entire ECU for sleep mode
 *                  - fast and systematic wakeup behavior
 *                  - shutdown of the ECU
 *
 *                To be very independent of different system designs e.g. different Modules to initialize,
 *                external/internal Watchdog, etc., the ECU State Manager provides over a mechanism named "callouts"
 *                a way to adapt the startup and shutdown behavior. The system designer must fill the proper code into
 *                the callouts.
 *********************************************************************************************************************/

/**********************************************************************************************************************
    Bswmd Version : 4.08.00
    Project       : EPS.ecuc
    Generated     : 2014-01-31 04:28 pm
    Licensee      : Vector AUTOSAR Basic Software (MICROSAR)
 
    This file is generated by DaVinci Configurator Base - DAVINCICFG.EXE V4.0.67.0.

 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Name                          Initials      Company
 *  -------------------------------------------------------------------------------------------------------------------
 *  Christian Marchl              Chm           Vctr Informatik GmbH
 *  Bethina Mausz                 Bmz           Vctr Informatik GmbH
 *  -------------------------------------------------------------------------------------------------------------------
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Version   Date        Author  Change Id     Description
 *  ------------------------------------------------------------------------------------------------------------------
 *  03.00.01  2007-09-26  Chm     ESCAN00022372 Quality assurance activities necessary for Component SysService_EcuM
 *  03.00.02  2007-11-21  Chm     ESCAN00023354 No changes
 *  03.00.03  2007-12-06  Chm     ESCAN00022871 No changes here
 *                                -             Added Revision History
 *  04.00.00  2008-03-01  Chm     ESCAN00024563 No changes here
 *                                ESCAN00023356 No changes here
 *                                ESCAN00024323 No Changes here
 *                                ESCAN00027863 No Changes here
 *  04.00.01  2008-04-16  Chm     ESCAN00026037 No Changes here
 *                                ESCAN00026537 Adapted template value
 *                                ESCAN00026471 No changes here
 *  04.01.00  2008-05-15  Chm     -             No Changes here
 *  04.01.01  2008-06-02  Chm     -             No Changes here
 *  04.01.02  2008-06-06  Chm     ESCAN00027459 Changed compiler abstraction in callout function
 *                                              EcuM_DeterminePbConfiguration()
 *                                ESCAN00027313 No changes here
 *  04.01.03  2008-06-17  Chm     ESCAN00027659 No Changes here
 *  04.02.00  2008-06-30  Chm     ESCAN00027955 No Changes here
 *  04.03.00  2008-07-23  Chm     ESCAN00028372 No Changes here
 *                                ESCAN00028511 No Changes here
 *  04.03.01  2008-08-08  Bmz     -             No Changes here
 *  04.03.02  2008-08-13  Bmz     ESCAN00029221 No changes here
 *  04.03.03  2008-09-01  Chm     ESCAN00029621 No changes here
 *                                ESCAN00029300 No changes here
 *  04.03.04  2008-09-24  Chm     ESCAN00027708 No changes here
 *                                ESCAN00029799 No changes here
 *                                ESCAN00029815 No changes here
 *                                ESCAN00029313 No changes here
 *  04.04.00  2008-10-22  Chm     ESCAN00030516 Added PreCompile Variant support
 *  05.00.00  2008-11-28  Chm     ESCAN00031216 No changes here
 *                                ESCAN00031214 Added file EcuM_PrivateCfg.h to component
 *                                ESCAN00030497 No changes here
 *                                ESCAN00030132 No changes here
 *                                ESCAN00031520 Added precompile switch for activation of
 *                                              EcuM_GeneratorCompatibilityError() callout
 *                                ESCAN00031786 No changes here
 *                                ESCAN00031787 No changes here
 *  05.01.00  2009-02-19  Chm     ESCAN00032011 No changes here
 *            2009-02-19  Chm     ESCAN00032502 Changed copyright
 *            2009-02-19  Chm     ESCAN00033069 No changes here
 *            2009-02-20  Chm     ESCAN00031852 No changes here
 *            2009-02-23  Chm     ESCAN00029165 Changed EcuM_GeneratorCompatibilityError() accordingly
 *            2009-02-24  Chm     ESCAN00031789 No changes here
 *            2009-03-04  Chm     ESCAN00033480 No changes here
 *            2009-03-09  Chm     ESCAN00033718 Added V_USE_DUMMY_STATEMENT
 *            2009-03-16  Chm     ESCAN00033834 No changes here
 *  05.02.00  2009-05-19  Chm     ESCAN00035001 No changes here
 *            2009-07-07  Chm     ESCAN00036192 No changes here
 *  05.03.00  2009-07-13  Chm     ESCAN00036369 No changes here
 *            2009-07-13  Chm     ESCAN00036370 No changes here
 *            2009-07-13  Chm     ESCAN00035287 No changes here
 *            2009-07-15  Chm     ESCAN00036441 No changes here
 *            2009-07-16  Chm     ESCAN00035917 No changes here
 *            2009-07-16  Chm     ESCAN00035535 Added support of UserBlocks in file generation.
 *            2009-07-17  Chm     ESCAN00036348 No changes here
 *            2009-07-16  Chm     ESCAN00035536 No changes here
 *            2009-07-21  Chm     ESCAN00034788 No changes here
 *  05.03.01  2009-10-22  Chm     ESCAN00037381 No changes here
 *  05.03.02  2009-12-11  Chm     ESCAN00039720 No changes here
 *            2009-12-11  Chm     ESCAN00037612 No changes here
 *            2009-12-14  Chm     ESCAN00039748 No changes here
 *            2009-12-15  Chm     ESCAN00034936 No changes here
 *            2009-12-21  Chm     ESCAN00039882 No changes here
 *            2010-02-19  Chm     ESCAN00040987 No changes here
 *            2010-02-23  Chm     ESCAN00041075 No changes here
 *  05.03.03  2010-04-14  Chm     ESCAN00041836 Added endless loop in default implementation of EcuM_GeneratorCompatibilityError() if DevErrorDetect is OFF
 *            2010-04-19  Chm     ESCAN00041426 Added execution of 'VLibVersionCheck' in EcuM_AL_DriverInitZero
 *            2010-04-24  Chm     ESCAN00041446 No changes here
 *            2010-04-24  Chm     ESCAN00041827 No changes here
 *  05.03.04  2010-07-29  Bmz     ESCAN00044245 No changes here
 *            2010-07-29  Bmz     ESCAN00044246 No changes here
 *            2010-07-29  Bmz     ESCAN00043065 V_SUPRESS_EXTENDED_VERSION_CHECK - wrong spelling
 *  05.04.00  2010-10-18  Bmz     ESCAN00044990 No changes here
 *                                ESCAN00046061 Added new callout: EcuM_McuSetMode
 *  05.06.00  2010-11-26  Bmz     ESCAN00046158 No changes here
 *                                ESCAN00047183 No changes here
 *                                ESCAN00047434 No changes here
 *                                ESCAN00045138 No changes here
 *            2011-01-26  Bmz     Prefix generation for DEM-ERRORS inserted in GenerationS.xml
 *                                G601 updated
 *            2011-02-03  Bmz     ESCAN00048364 No changes here
 *  05.06.01  2011-03-14  Bmz     ESCAN00049201 Mcu_SetMode call moved into USER CODE from EcuM_McuSetMode
 *  05.07.00  2011-04-26  Bmz     ESCAN00049111 No changes here
 *  05.07.01  2011-05-12  Bmz     ESCAN00049989 No changes here
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK User Version>                         DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
/* Version Control:
 * Date Created:      Wed Jul 17 11:00:00 2013
 * %version:          4 %
 * %derived_by:       zz4r1x %
 * %date_modified:    Fri Jan 25 10:12:40 2013 %
 *---------------------------------------------------------------------------------------------------------------------
 * Date      Rev      Author    Change Description                                                               SCR #
 * --------  -------  --------  ------------------------------------------------------------------------------  -------
 * 02/14/14   1       OT        Initial version
 */
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

/*********************************************************************************************************************
    INCLUDES
 *********************************************************************************************************************/
 
#define ECUM_CALLOUT_STUBS_SOURCE
#include "EcuM_Cbk.h"
#include "EcuM.h"

/*<ECUM_DEV_ERROR_DETECT_INCLUDE_FILE>*/
#include "Det.h"
/*</ECUM_DEV_ERROR_DETECT_INCLUDE_FILE>*/

#include "Mcu.h"
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK User Includes>                        DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

extern FUNC(Std_ReturnType, RTE_IOHWABSTRACTION_APPL_CODE) IoHwAb_SetTODReset(IoHwAb_BoolType signal);
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

/*********************************************************************************************************************
    VERSION CHECK
 *********************************************************************************************************************/
#if (ECUM_CBK_MAJOR_VERSION != (5u))
# error "Incompatible ECUM_CBK_MAJOR_VERSION with this EcuM Implementation!"
#endif

#if (ECUM_CBK_MINOR_VERSION != (7u))
# error "Incompatible ECUM_CBK_MINOR_VERSION with this EcuM Implementation!"
#endif

#if (ECUM_AR_MAJOR_VERSION != (1u))
# error "Incompatible ECUM_AR_MAJOR_VERSION with this EcuM Implementation!"
#endif

#if (ECUM_AR_MINOR_VERSION != (2u))
# error "Incompatible ECUM_AR_MINOR_VERSION with this EcuM Implementation!"
#endif

#if !defined (V_USE_DUMMY_STATEMENT)
# error "The define V_USE_DUMMY_STATEMENT shall be defined either in Compiler_Cfg.h or as parameter for the Compiler"
#endif

#ifndef V_SUPPRESS_EXTENDED_VERSION_CHECK
extern Std_ReturnType VLibVersionCheck(void);
#endif
/**********************************************************************************************************************
 *  CALLOUT FUNCTIONS
 **********************************************************************************************************************/
#define ECUM_START_SEC_CODE
#include "MemMap.h"

#if (STD_ON == ECUM_ON_RTESTARTUP_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnRTEStartup(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnRTEStartup>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnRTEStartup() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnRTEStartup() */
#endif

#if (STD_ON == ECUM_ON_ENTER_RUN_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnEnterRun(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnEnterRun>                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

  /* Add implementation of EcuM_OnEnterRun() */
  EcuM_RequestRUN(1);
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnEnterRun() */
#endif

#if (STD_ON == ECUM_ON_EXIT_RUN_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnExitRun(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnExitRun>                      DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnExitRun() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnExitRun() */
#endif

#if (STD_ON == ECUM_ON_EXIT_POST_RUN_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnExitPostRun(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnExitPostRun>                   DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnExitPostRun() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnExitPostRun() */
#endif

#if (STD_ON == ECUM_ON_PREP_SHUTDOWN_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnPrepShutdown(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnPrepShutdown>                  DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnPrepShutdown() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnPrepShutdown() */
#endif

#if (STD_ON == ECUM_ON_GO_SLEEP_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnGoSleep(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnGoSleep>                       DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnGoSleep() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnGoSleep() */
#endif

#if (STD_ON == ECUM_ON_GO_OFF_ONE_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnGoOffOne(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnGoOffOne>                       DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnGoOffOne() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnGoOffOne() */
#endif

#if (STD_ON == ECUM_ON_GO_OFF_TWO_CALLOUT)
FUNC(void, ECUM_CODE) EcuM_OnGoOffTwo(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnGoOffTwo>                       DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnGoOffTwo() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnGoOffTwo() */
#endif

FUNC(void, ECUM_CODE) EcuM_GenerateRamHash(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_GenerateRamHash>                 DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_GenerateRamHash() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_GenerateRamHash() */

FUNC(uint8, ECUM_CODE) EcuM_CheckRamHash(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_CheckRamHash>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_CheckRamHash() */
  return (1u);
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_CheckRamHash() */

FUNC(void, ECUM_CODE) EcuM_AL_SwitchOff(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_AL_SwitchOff>                    DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  IoHwAb_SetTODReset(FALSE);
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_AL_SwitchOff() */

FUNC(void, ECUM_CODE) EcuM_AL_DriverInitZero(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_AL_DriverInitZero>               DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_AL_DriverInitZero() */

# ifndef V_SUPPRESS_EXTENDED_VERSION_CHECK
    if (E_NOT_OK == VLibVersionCheck()) 
    {
#	    if (STD_ON == ECUM_DEV_ERROR_DETECT) 
		    EcuM_Det_Errorhook(ECUM_SID_DRIVER_INIT_ZERO, ECUM_E_EXTENDED_LIB_VERSION_CHECK_FAILED);
#     else
        /* remove this line in production code and add the desired functionality to resolve generator incompatibilities 
         * this line may raise a compiler warning, due to the fact that the user is responsible for the specific 
         * implementation this warning is acceptable. 
         */
        volatile uint8 removeMeInProductionCode = 1;
        while (removeMeInProductionCode);
#	    endif
    }
#endif
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_AL_DriverInitZero() */

#if (ECUM_CONFIG_VARIANT == ECUM_VARIANT_POSTBUILD)
FUNC(EcuM_ConfigRefType, ECUM_CODE) EcuM_DeterminePbConfiguration(void)
{

/*<ECUM_INITIAL_CONFIGURATION_SET_NAME>*/
    /* The following configuration set names are available:
     * ----------------------------------------------------
     Module in variant PRE-COMPILE: no configuration set available
     */
/*</ECUM_INITIAL_CONFIGURATION_SET_NAME>*/ 

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_DeterminePbConfiguration>        DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_DeterminePbConfiguration() */

//#error "EcuM_Callout_Stubs.c: Please select one of the ECUM config sets which should be used for initialization from the list above"
return((EcuM_ConfigType*)&EcuMConfiguration);
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_DeterminePbConfiguration() */
#endif

#if (STD_ON == ECUM_ON_WAKEUP_REACTION_CALLOUT)
FUNC(EcuM_WakeupReactionType, ECUM_CODE) EcuM_OnWakeupReaction(EcuM_WakeupReactionType wact)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_OnWakeupReaction>                DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
  /* Add implementation of EcuM_OnWakeupReaction() */
  return  wact;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_OnWakeupReaction() */
#endif

FUNC(void, ECUM_CODE) EcuM_EnableWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_EnableWakeupSources>             DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_EnableWakeupSources() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_EnableWakeupSources() */

FUNC(void, ECUM_CODE) EcuM_DisableWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_DisableWakeupSources>            DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_DisableWakeupSources() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_DisableWakeupSources() */

FUNC(void, ECUM_CODE) EcuM_StartWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_StartWakeupSources>              DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_StartWakeupSources() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_StartWakeupSources() */

FUNC(void, ECUM_CODE) EcuM_StopWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_StopWakeupSources>               DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_StopWakeupSources() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_StopWakeupSources() */

FUNC(void, ECUM_CODE) EcuM_CheckWakeup(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_CheckWakeup>                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_CheckWakeup() */

  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_CheckWakeup() */

FUNC(void, ECUM_CODE) EcuM_CheckValidation(EcuM_WakeupSourceType wakeupSource)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_CheckValidation>                 DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    wakeupSource = wakeupSource; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif
  /* Add implementation of EcuM_CheckValidation() */

  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_CheckValidation() */

#if ((!defined (V_SUPPRESS_EXTENDED_VERSION_CHECK)) || (ECUM_GENERATOR_COMPATIBILITY_ERROR == STD_ON))
FUNC(void, ECUM_CODE) EcuM_GeneratorCompatibilityError(uint16 ModuleId, uint8 InstanceId)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_GeneratorCompatibilityError>     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
# if (ECUM_DEV_ERROR_DETECT == STD_ON)
    EcuM_Det_Errorhook(ECUM_SID_GENERATOR_COMPATIBILITY_ERROR, ECUM_E_GENERATOR_COMPATIBILITY);
# else
    /* remove this line in production code and add the desired functionality to resolve generator incompatibilities 
     * this line may raise a compiler warning, due to the fact that the user is responsible for the specific 
     * implementation this warning is acceptable. 
     */
    volatile uint8 removeMeInProductionCode = 1;
    while(removeMeInProductionCode);
# endif

# if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    ModuleId = ModuleId; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
    InstanceId = InstanceId; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
# endif

  /* Add implementation of EcuM_GeneratorCompatibilityError() */
  return;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_GeneratorCompatibilityError() */
#endif

FUNC(void, ECUM_CODE) EcuM_McuSetMode(uint8 mode_u8)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_McuSetMode>     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

  /* add MCU relevant code which is necessary before entering SLEEP state */

  /* DO NOT remove this function call */
  Mcu_SetMode(mode_u8);

  /* add MCU relevant code which is necessary after leaving SLEEP state */

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

  return;
} /* End of EcuM_GeneratorCompatibilityError() */




#define ECUM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 *//* MISRA-C:2004 Rule 19.1: violation due to AUTOSAR requirement for Memory Mapping */

#define ECUM_START_SEC_CODE_SET_BOOT_TARGET
#include "MemMap.h" /* PRQA S 5087 *//* MISRA-C:2004 Rule 19.1: violation due to AUTOSAR requirement for Memory Mapping */

FUNC(Std_ReturnType, ECUM_CODE_BOOT_TARGET) EcuM_Appl_SelectBootTarget(EcuM_BootTargetType BootTarget_t)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_Appl_SelectBootTarget>           DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    BootTarget_t = BootTarget_t; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif

  return E_OK;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_Appl_SelectBootTarget() */

#define ECUM_STOP_SEC_CODE_SET_BOOT_TARGET
#include "MemMap.h" /* PRQA S 5087 *//* MISRA-C:2004 Rule 19.1: violation due to AUTOSAR requirement for Memory Mapping */


#define ECUM_START_SEC_CODE_GET_BOOT_TARGET
#include "MemMap.h" /* PRQA S 5087 *//* MISRA-C:2004 Rule 19.1: violation due to AUTOSAR requirement for Memory Mapping */

FUNC(Std_ReturnType, ECUM_CODE_BOOT_TARGET) EcuM_Appl_GetBootTarget
(
  P2VAR(EcuM_BootTargetType, AUTOMATIC, ECUM_VAR_BOOT) BootTarget_pt
)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           <USERBLOCK EcuM_Appl_GetBootTarget>              DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#if (V_USE_DUMMY_STATEMENT == STD_ON)
    /* dummy assignment to prevent compiler warnings on most of the compilers. */
    BootTarget_pt = BootTarget_pt; /* PRQA S 3199 *//* MISRA-C:2004 redundancy: dummy assignment for unused parameter */
#endif

  return E_OK;
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           </USERBLOCK>                                     DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
} /* End of EcuM_Appl_GetBootTarget() */

#define ECUM_STOP_SEC_CODE_GET_BOOT_TARGET
#include "MemMap.h" /* PRQA S 5087 *//* MISRA-C:2004 Rule 19.1: violation due to AUTOSAR requirement for Memory Mapping */

/**********************************************************************************************************************
 *  END OF FILE: ECUM_CALLOUT_STUBS.C
 *********************************************************************************************************************/

