#define 	D_TESTFAILEDBIT_CNT_B8							0x01U
#define 	D_TESTFAILEDTHISOPCYCLEBIT_CNT_B8				0x02U
#define 	D_PENDINGDTCBIT_CNT_B8							0x04U
#define 	D_CONFIRMEDDTCBIT_CNT_B8						0x08U
#define 	D_TESTNOTCOMPLETESINCELASTCLEARBIT_CNT_B8		0x10U
#define 	D_TESTFAILEDSINCELASTCLEARBIT_CNT_B8			0x20U
#define 	D_TESTNOTCOMPLETETHISOPCYCLEBIT_CNT_B8			0x40U
#define 	D_WARNINGINDICATORBIT_CNT_B8					0x80U